
Below are relevant files from two R packages related to my repbox project

# Package repboxDRF

{repboxDRF}


# Package repboxStataReg


# FILE: /home/rstudio/repbox/repboxStataReg/DESCRIPTION
```
Package: repboxStataReg
Type: Package
Title: Extraction of regression information from Stata reproduction run (before metareg)
Version: 0.1.0
Authors@R: c(
    person(
      "Sebastian", "Kranz",
      email = "sebastian.kranz@uni-ulm.de",
      role = c("aut", "cre")
    )
  )
Description: Core part of previous huge repboxReg package. 
  Only the functionality related to the original reproduction
  run, no metareg stuff.
License: GPL >= 2.0
Encoding: UTF-8
LazyData: true
Depends: repboxDB, repboxUtils, repboxDRF, repboxStata
```
# END OF FILE: /home/rstudio/repbox/repboxStataReg/DESCRIPTION

-----------------------------------------------------------


# FILE: /home/rstudio/repbox/repboxStataReg/R/extract_reg_stata.R
```
# Will be called from repboxStata
#
# Extracts specified regression information
#
rsr_extract_stata_reg_output = function(project_dir, run.df=NULL, dotab=NULL, save=TRUE) {
  restore.point("rsr_extract_stata_reg_output")

  #if (is.null(runid_map)) {
  #  runid_map = readRDS(file.path(project_dir, "repbox/stata/runid_repbox_map.Rds"))
  #}

  if (is.null(run.df) | is.null(dotab)) {
    repbox_results = readRDS(file.path(project_dir, "repbox/stata/repbox_results.Rds"))
    run.df = repbox_results$run.df
    dotab = repbox_results$dotab
  }

  artid = basename(project_dir)
  #++++++++++++++++++++++++++++++++++++++++++++++++++
  # 1. Extract TSV information stored by esttab
  #++++++++++++++++++++++++++++++++++++++++++++++++++

  res.dir = file.path(project_dir,"repbox/stata/tsv")
  files = list.files(res.dir,glob2rx(paste0("*.dta")),full.names = TRUE)

  bfiles = basename(files)
  donum = str.left.of(bfiles, "_") %>% as_integer()
  str = str.right.of(bfiles,"_")
  line = str.left.of(str, "_") %>% as_integer()
  str = str.right.of(str,"_")
  counter = str.remove.ends(str, right=4) %>% as_integer()

  regtab = tibble(regresfile=files,donum=donum,line=line,counter=counter) %>%
    arrange(donum, line, counter) %>%
    group_by(donum, line) %>%
    mutate(run = seq_len(n())) %>%
    ungroup()

  regtab$ct = lapply(regtab$regresfile, function(file) {
    restore.point("inner.read.regres")
    regres = haven::read_dta(file)
    old.cols = c("eq","parm","label","estimate","stderr","dof", "z","p","min95","max95")
    new.cols = c("eq","var","label", "coef","se","dof", "t","p","ci_low","ci_up")
    regres = rename.cols(regres, old.cols, new.cols)
    regres = regres[,intersect(new.cols, colnames(regres)), drop=FALSE]
    if (!"eq" %in% colnames(regres)) {
      regres$eq = rep("", NROW(regres))
    }
    regres
  })
  regtab = select(regtab, -regresfile)



  #++++++++++++++++++++++++++++++++++++++++++++++++++
  # 2. Extract regression information stored in logs
  #++++++++++++++++++++++++++++++++++++++++++++++++++

  dir = file.path(project_dir, "repbox/stata/logs")
  log.files = list.files(dir,glob2rx("log_*.log"),full.names = TRUE)

  reg.log = lapply(log.files, function(file) {
    log.txt = readLines(file,warn=FALSE)  %>% enc2utf8()
    bdf = extract.inject.blocks(log.txt, type="REG_ERETURN")
    bdf$er = lapply(bdf$str,parse.ereturn.injection)
    bdf
  }) %>% bind_rows()

  regtab = left_join(regtab, select(reg.log, donum, line, counter, er), by=c("donum","line","counter"))

  #++++++++++++++++++++++++++++++++++++++++++++++++++
  # 3. Merge with run.df
  #++++++++++++++++++++++++++++++++++++++++++++++++++

  regtab = left_join(regtab,run.df, by=c("donum","line","counter"))

  # UPDATE: Only consider regression where missing_data = FALSE
  # Otherwise we likely have faulty regressions that use an earlier data set
  # Also ignore regression results with run error
  regtab = regtab[regtab$has.data & !regtab$runerr,]


  regtab$artid = artid

  # merge with dotab to get doid
  regtab = regtab %>% left_join(dotab %>% select(donum, doid), by="donum")

  #colnames(regtab)
  cols = c("artid", "runid", "donum", "doid", "line", "counter","cmd", "cmdline","ct","er", "datasig", "timevar" ,"panelvar", "tdelta",        "runerr",        "runerrcode",    "runerrmsg",     "runsec", "orgline", "in.program", "has.data")
  regtab = regtab[,cols]


  if (save) {
    saveRDS(regtab, file.path(project_dir,"repbox/stata/regtab.Rds"))
  }

  regtab
}



# Used to extract additional regression information
parse.ereturn.injection = function(str) {
  restore.point("parse.ereturn.injection")

  # scalars
  start = which(str=="scalars:")+1
  if (length(start)>0) {
    end = min(which(str=="" & 1:NROW(str)>start))-1
    svec = trimws(str[start:end])
    var = trimws(str.left.of(svec,"=")) %>% str.remove.ends(2,1)
    val = suppressWarnings(as.numeric(str.right.of(svec,"=") %>% trimws()))
    scalars = as.list(val)
    names(scalars) = var
  } else {
    scalars = list()
  }

  # macros (contains e.g. depvar)
  start = which(str=="macros:")+1
  if (length(start)>0) {
    end = min(which((str=="" | startsWith(str, "#~# END INJECT")) & 1:NROW(str)>start))-1
    svec = trimws(str[start:end])
    var = trimws(str.left.of(svec,":")) %>% str.remove.ends(2,1)
    val = str.right.of(svec,":") %>% trimws()%>% str.remove.ends(1,1)
    macros = as.list(val)
    names(macros) = var
  } else {
    macros = list()
  }

  as_tibble(c(scalars,macros))
}



```
# END OF FILE: /home/rstudio/repbox/repboxStataReg/R/extract_reg_stata.R

-----------------------------------------------------------


# FILE: /home/rstudio/repbox/repboxStataReg/R/inject_reg_stata.R
```

# Will be called from repboxStata
#
# Inject regression specific information
injection.reg = function(txt, lines=seq_along(txt),do, opts=rbs.opts()) {
  restore.point("injection.reg")

  repbox.dir = file.path(do$project_dir,"repbox/stata")
  res.dir = file.path(repbox.dir,"tsv")

  res.files = paste0(res.dir,"/",do$donum,"_",  lines,"_`repbox_local_cmd_count'",".dta")

  paste0('
local repbox_reg_rc = _rc
', end.injection(do$donum, lines, "RUNCMD",do),'
* REGRESSION INJECTION START
if (`repbox_reg_rc\' == 0) {
  parmest, label saving("', res.files,'", replace)

',post.injection(txt,lines,do=do, report.xtset=TRUE),'
  display "#~# INJECT REG_ERETURN ', do$donum,' ', lines,' `repbox_local_cmd_count\'"
  ereturn list
  display "#~# END INJECT REG_ERETURN ',do$donum,' ', lines,' `repbox_local_cmd_count\'"
}
else {
  display "#~# REGRESSION COMMAND FAILED ',do$donum,' ', lines,' `repbox_local_cmd_count\' rc=`repbox_reg_rc\'"
}

* REGRESSION INJECTION END
')
}
```
# END OF FILE: /home/rstudio/repbox/repboxStataReg/R/inject_reg_stata.R

-----------------------------------------------------------


# FILE: /home/rstudio/repbox/repboxStataReg/R/rsr.R
```
example = function() {
  library(repboxStataReg)
  # Should point to this project dir
  overwrite=TRUE
  project_dir = "~/repbox/projects/aejapp_11_2_10"
  parcels = list()

  if (FALSE)
    rstudioapi::filesPaneNavigate(project_dir)

  rsr_make_reg_info(project_dir, overwrite=TRUE)
}

# Stores cmdpart parcels and internal reg info in repbox/stata dir
# we cannot yet store any regcoef etc parcels
# since that requires metaregBase semantic parsing with data set info
rsr_make_reg_info = function(project_dir, overwrite=FALSE, parcels=list(), repbox_results=repbox_load_internal_repbox_results(project_dir)) {
  restore.point("rsr_make_reg_info")
  parcels = repdb_load_parcels(project_dir, "stata_run_cmd")
  run_df = repboxDRF::repbox_get_run_df(project_dir = project_dir, parcels=parcels)
  parcels = rsr_make_cmdpart_parcels(project_dir = project_dir, overwrite=overwrite, run_df=run_df)
  rsr_make_stata_reg_run_info_parcel(project_dir, parcels=parcels,repbox_results=repbox_results)
  regtab = rsr_extract_stata_reg_output(project_dir)

  parcels
}

rsr_make_cmdpart_parcels = function(project_dir,  overwrite=FALSE, parcels=list(), run_df = repboxDRF::repbox_get_run_df(project_dir = project_dir, parcels=parcels)) {
  restore.point("rsr_make_cmdpart_parcels")

  if (!overwrite) {
    if (repboxDB::repdb_has_parcel(project_dir, "reg_cmdpart")) {
      return(parcels)
    }
  }

  repdb_dir = file.path(project_dir, "repdb")

  rows = which(run_df$cmd_type %in% c("reg"))
  cp_df = cmdparts_of_stata_reg(run_df$cmdline[rows]) %>%
    arrange(str_row)
  cp_df$runid = run_df$runid[rows[cp_df$str_row]]
  parcels[["reg_cmdpart"]] = cp_df

  repboxDB::repdb_save_parcels(parcels[c("reg_cmdpart")],dir=repdb_dir)

  rows = which(run_df$cmd_type %in% c("quasi_reg"))
  if (length(rows)==0) return(parcels)

  cp_df = cmdparts_of_stata_reg(run_df$cmdline[rows]) %>%
    arrange(str_row)
  cp_df$runid = run_df$runid[rows[cp_df$str_row]]
  parcels[["quasi_reg_cmdpart"]] = cp_df
  repboxDB::repdb_save_parcels(parcels[c("quasi_reg_cmdpart")],dir=repdb_dir)

  parcels
}


# Only saves run_info after regression run
# Regression information will be stored after metareg run
rsr_make_stata_reg_run_info_parcel = function(project_dir, parcels=list(), repbox_results=repbox_load_internal_repbox_results(project_dir)) {
  restore.point("repbox_save_stata_reg_run_parcels")

  parcels = repdb_load_parcels(project_dir, c("stata_run_info","stata_file"), parcels=parcels)
  artid = basename(project_dir)

  res = repbox_results

  # No Stata run results stored
  if (is.null(res)) {
    return(parcels)
  }

  dotab = res$dotab
  dotab$file_path = str.right.of(dotab$file, paste0("/",artid,"/mod/"))

  if (!has.col(res$tab,"in_loop")) {
    cat("\nNote there was no 'in_loop' col in repbox_results$tab\n")
    res$tab$in_loop = NA_integer_
  }

  run_df = res$run.df %>%
    mutate(
      artid = artid,
      found_path = file_path_relative_to_supp(foundfile, paste0("/", artid, "/mod/"),wdir = wdir, supp.dir = paste0(project_dir, "/", artid, "/mod/"))
    ) %>%
    rename(

      start_time = stime,
      end_time = etime,
      errcode = runerrcode,
      errmsg = runerrmsg,
      out_img_file = out.img.file
    ) %>%
    left_join(select(dotab, donum, file_path), by="donum") %>%
    left_join(select(dotab, rootdonum = donum, root_file_path = file_path), by="rootdonum")

  run_df$runid = seq_len(NROW(run_df))
  script_df = parcels$stata_file
  run_df = left_join(run_df, select(script_df, file_path, script_num), by="file_path")

  # Don't save detailed run results after reg run

  #repdb_check_data(run_df,"stata_run_cmd")
  #repdb_check_data(run_df,"stata_run_log")

  #parcels$stata_run_cmd = run_df
  #parcels$stata_run_log = run_df

  run_info = run_df %>%
    summarize(
      artid = first(artid),
      runtype = "reg",
      runs = n(),
      ok_runs = sum(is.true(has.data & !runerr)),
      no_dat_runs = sum(!is.true(has.data)),
      err_runs = sum(runerr & is.true(has.data)),
      reg_runs = sum(is.regcmd),
      no_dat_reg_runs = sum(is.regcmd & !is.true(has.data)),
      err_reg_runs = sum(is.regcmd & runerr & is.true(has.data)),
      ok_reg_runs = reg_runs-err_reg_runs-no_dat_reg_runs,
      start_time = first(start_time[!is.na(start_time)]),
      end_time = last(end_time[!is.na(end_time)]),
      run_sec = time.diff(start_time, end_time)
    )






  org_run_info = parcels$stata_run_info

  if (NROW(org_run_info)==0) {
    if (run_info$err_runs >0) {
      repbox_problem(msg = paste0("The Stata run had ", run_info$err_runs, " commands that threw an error"), type = "stata_err",fail_action = "msg")
    }
    if (run_info$no_dat_runs >0) {
      repbox_problem(msg = paste0(run_info$no_dat_runs, " of the ", run_info$runs, " run commands had a missing data set."), type = "stata_no_dat",fail_action = "msg")
    }

  } else {
    if (run_info$err_runs > org_run_info$err_runs) {
      repbox_problem(msg = paste0("The Stata run which stored regression information had more errors than the original run."), type = "stata_reg_err",fail_action = "msg")
    } else if (run_info$runs != org_run_info$runs) {
      repbox_problem(msg = paste0("The Stata run which stored regression information executed a different number of commands than the original run."), type = "stata_reg_runs_diff",fail_action = "msg")
    } else if (run_info$err_runs < org_run_info$err_runs) {
      repbox_problem(msg = paste0("The Stata run  which stored regression information had fewer errors than the original run."), type = "stata_reg_err",fail_action = "msg")
    }
  }
  parcels$stata_reg_run_info = run_info

  repdb_save_parcels(parcels[c("stata_reg_run_info")], file.path(project_dir, "repdb") )
  invisible(parcels)
}
```
# END OF FILE: /home/rstudio/repbox/repboxStataReg/R/rsr.R

-----------------------------------------------------------


# FILE: /home/rstudio/repbox/repboxStataReg/R/static_reg.R
```
# Static code analysis of regression commands
# Note that the static code can still contain Stata macros
# and thus cannot be as reliably analysed as the command line
# we get from our dynamic analysis in which macros have been
# replaced.

example = function() {
  project_dir = "~/repbox/projects_static/aejapp_10_1_1"
  parcels = repboxDB::repdb_load_parcels(project_dir, "reg_stata_cmd")
  reg_cmd = parcels$reg_stata_cmd$reg_stata_cmd
  reg_cmd$sregnum = 1:NROW(reg_cmd)
  reg_df = static_reg_cmd_to_reg_df(reg_cmd)
}

static_reg_cmd_to_reg_df = function(reg_cmd) {
  restore.point("static_reg_cmd_to_reg_df")
  if (NROW(reg_cmd)==0) return(NULL)
  reg_cmd$sregnum = seq_len(NROW(reg_cmd))
  cmdpart = cmdparts_of_stata_reg(reg_cmd$cmdline)
  cmdpart$artid = reg_cmd$artid[cmdpart$str_row]
  cmdpart$step  = cmdpart$sregnum = cmdpart$str_row
  opts_df = cmdpart_to_opts_df(cmdpart)

  unique(cmdpart$part)
  unique(cmdpart$tag)

  cols = union(c("artid", "sregnum"), setdiff(colnames(reg_cmd), c("num_runs","num_err_runs","is_reg")))
  reg_cmd = reg_cmd[,cols]


  i = 1
  reg_df = bind_rows(lapply(seq_len(NROW(reg_cmd)), function(i) {
    #restore.point("hhsfkhf")
    reg=reg_cmd[i,]
    opts = opts_df[opts_df$step==i,]
    reg$opts_have_macro = isTRUE(any( has.substr(opts$opt_arg,"$") | has.substr(opts$opt_arg,"`")))
    se_info = try(se_stata_to_repdb(reg_cmd$cmd[i], opts),silent = TRUE)

    if (is(se_info,"try-error")) {
      cat(paste0("\nCould not parse se info:\n   ", reg$cmdline,"\n"))
      reg[c("se_category","se_type","se_args")] = rep(NA_character_,3)
    } else {
      reg[c("se_category","se_type","se_args")] = se_info[c("se_category","se_type","se_args")]
    }
    reg
  }))

  cmd_sum = cmdpart %>%
    group_by(artid, sregnum) %>%
    summarize(
      has_weights = "weight_str" %in% part,
      has_absorb = "absorb" %in% tag,
      specifies_se = "se" %in% tag,
      has_if = "if_str" %in% part,
      has_in = "in_str" %in% part,
      has_opt = "opt_str" %in% part
    )

  reg_df = reg_df %>% left_join_overwrite(cmd_sum, by = c("artid","sregnum"))
  reg_df$uses_macro = has.substr(reg_df$cmdline,"`") & has.substr(reg_df$cmdline,"$")

  reg_df

}
```
# END OF FILE: /home/rstudio/repbox/repboxStataReg/R/static_reg.R

-----------------------------------------------------------


# FILE: /home/rstudio/repbox/repboxStataReg/R/utils.R
```
touchFile = function (pathname, ...) {
  if (!exists("Sys.setFileTime", mode = "function")) {
    Sys.setFileTime <- function(path, ...) {
      info <- file.info(pathname)
      if (info$isdir) {
        stop(sprintf("In R v%s, it is not possible to change the timestamp of a directory: %s",
                     getRversion(), pathname))
      }
      con <- NULL
      on.exit({
        if (!is.null(con)) close(con)
      })
      if (info$size == 0) {
        con <- file(pathname, open = "w")
      }
      else {
        con <- file(pathname, open = "r+b")
        seek(con = con, where = 0, origin = "start",
             rw = "read")
        bfr <- readBin(con = con, what = raw(), n = 1)
        seek(con = con, where = 0, origin = "start",
             rw = "write")
        writeBin(con = con, bfr)
      }
      invisible(TRUE)
    }
  }
  pathname <- as.character(pathname)
  nPathnames <- length(pathname)
  if (nPathnames == 0L)
    return(invisible(NULL))
  if (nPathnames > 1L) {
    res <- lapply(pathname, FUN = touchFile, ...)
    res <- Reduce(c, res)
    return(invisible(res))
  }
  if (!file.exists(pathname))
    stop("No such file: ", pathname)
  info <- file.info(pathname)
  oldTimestamp <- info$mtime
  if (!Sys.setFileTime(pathname, time = Sys.time())) {
    cat("\nFailed to set timestamp: ", pathname)
  }
  invisible(oldTimestamp)
}


rstudio_job = function(name, expr, libs=NULL, wdir = getwd(), script.dir = tempdir(), importEnv=TRUE) {
  expr = substitute(expr)
  restore.point("as_job")
  code = deparse1(expr)

  #code = paste0('setwd("',wdir,'")\n', code)
  if (!is.null(libs)) {
    code = paste0(paste0("library(", libs,")", collapse="\n"), "\n", code)
  }
  cat("\nRun \n\n",code,"\n\n")

  script.file = file.path(script.dir, paste0(name,".R"))
  writeLines(code, script.file)
  rstudioapi::jobRunScript(path = script.file,workingDir = wdir, name = name,importEnv = importEnv)

}



fe = function(val) {
  as.factor(val)
}


df.rows.to.list = function(df) {
  lapply(seq_len(NROW(df)), function(i) df[i,])
}

```
# END OF FILE: /home/rstudio/repbox/repboxStataReg/R/utils.R

-----------------------------------------------------------



# Package repboxUtils


# FILE: /home/rstudio/repbox/repboxUtils/DESCRIPTION
```
Package: repboxUtils
Type: Package
Title: Utility functions shared by several repbox packages
Version: 0.1.0
Author: Sebastian Kranz
Maintainer: Sebastian Kranz <sebastian.kranz@uni-ulm.de>
Description: Utility functions shared by several repbox packages
License: GPL >= 3.0
Encoding: UTF-8
LazyData: true
Depends: data.table, dplyr, digest
```
# END OF FILE: /home/rstudio/repbox/repboxUtils/DESCRIPTION

-----------------------------------------------------------


# FILE: /home/rstudio/repbox/repboxUtils/R/cmdpart_create.R
```
# Split Stata commands into parts that have a special cmdpart structure

cp_init = function(str, org_rows=NULL, str_part = "main") {
  cp = list(
    str=str,
    org_rows = org_rows,
    n = 0,
    start = rep(1, length(str)),
    df = cp_add_empty_df(df = NULL, size=max(length(str)*20))
  )
  if (!is.null(str_part)) {
    cp = cp_add_part_in_df(cp, seq_along(str),str_part,str,tag="", parent="")
  }

  cp
}

cp_add_empty_df = function(df = NULL,min_size=NROW(df), size=max(min_size,NROW(df))) {
  new_df = tibble(
    str_row = rep(NA, size),
    parent = rep("", size),
    part = rep("", size),
    content = rep("", size),
    tag = rep("",size),
    counter = rep(0, size)
    #ph = rep("", size)
  )
  if (is.null(df)) return(new_df)
  bind_rows(df, new_df)
}

cp_add_part_in_df = function(cp, str_rows, part, content, tag=NA, parent="main", counter=rep(0, length(part))) {
  restore.point("cp_add_part_in_df")
  n_add = max(length(str_rows), length(part), length(content))
  if (n_add == 0) return(cp)
  if (cp$n + n_add >= NROW(cp$df)) {
    cp$df = cp_add_empty_df(cp$df, n_add*2)
  }
  inds = (cp$n+1):(cp$n+n_add)

  cp$df$parent[inds] = parent
  cp$df$str_row[inds] = str_rows
  cp$df$part[inds] = part
  cp$df$content[inds] = content
  cp$df$tag[inds] = tag
  cp$df$counter[inds] = counter
  cp$n = cp$n + n_add
  cp
}

# Add extracted parts to cp
cp_add = function(cp, str_rows, start, end, part, tag=NA, use_counter=FALSE,ignore.right.ws=FALSE, parent="main") {
  restore.point("cp_add")
  n_add = length(str_rows)
  if (n_add==0) return(cp)
  if (cp$n + n_add >= NROW(cp$df)) {
    cp$df = cp_add_empty_df(cp$df, n_add*2)
  }

  inds = (cp$n+1):(cp$n+n_add)
  if (use_counter) {
    prev_count_df = cp$df[cp$df$part == part & cp$df$str_row %in% unique(str_rows),] %>%
      group_by(str_row) %>%
      summarize(
        count = n()
      )
    count_df = tibble(str_row = str_rows) %>%
      left_join(prev_count_df, by = "str_row")
    count_df$count[is.na(count_df$count)] = 0
    count_df$count = count_df$count+1


    counter = count_df$count[match(str_rows, count_df$str_row)]
    cp$df$counter[inds] = counter

    ph = paste0("{{", part, counter,"}}")
  } else {
    counter = rep(0, length(str_rows))
    ph = paste0("{{", part,"}}")
  }

  sstr = substring(cp$str[str_rows], start, end)
  if (ignore.right.ws) {
    len_ws = nchar(sstr) - nchar(trimws(sstr,"right"))
    end = end - len_ws
    sstr = substring(cp$str[str_rows], start, end)
  }


  content = sstr
  cp$df$parent[inds] = parent
  cp$df$str_row[inds] = str_rows
  cp$df$part[inds] = part
  cp$df$content[inds] = content
  cp$df$tag[inds] = tag
  cp$df$counter[inds] = counter
  #cp$df$ph[inds] = ph

  # Use stringi:stri_sub_replace since substring <- requires replacement
  # to be of same than original string
  cp$str[str_rows] = stringi::stri_sub_replace(cp$str[str_rows], from=start, to=end, replacement=ph)

  cp$added_inds = inds
  cp$start[str_rows] = cp$start[str_rows]+nchar(ph)
  cp$n = cp$n + n_add

  cp
}

cp_add_starts_with = function(cp, patterns, part, tag, use_counter = FALSE, ignore.right.ws = TRUE) {
  restore.point("set_cmdpart_starts_with")
  cp$did_change = FALSE
  unused = rep(TRUE, length(cp$str))
  start = cp$start
  sstr = substring(cp$str, cp$start)

  s = patterns[1]
  for (s in patterns) {
    str_rows = which(startsWith(sstr, s) & unused)
    if (length(str_rows)>0) {
      if (ignore.right.ws) {
        s = trimws(s, "right")
      }
      len = nchar(s)

      end = cp$start[str_rows]+len-1
      cp = cp_add(cp, str_rows = str_rows, start=start[str_rows], end=end, part=part, tag=tag, use_counter=use_counter)
      unused[str_rows] = FALSE
      cp$did_change = TRUE
    }
  }
  cp
}



find_ws_around = function(txt) {
  txt2 = trimws(txt,"left")
  ws_left = nchar(txt) - nchar(txt2)
  txt3 = trimws(txt2,"right")
  ws_right = nchar(txt2) - nchar(txt3)
  list(ws_left = ws_left, ws_right=ws_right, txt = txt3)
}

# TO DO: Allow to ignore white spaces on the left, but keep them in str
cp_add_left_of = function(cp, left_of, part, tag, use_counter = FALSE, include_split=FALSE, ignore.right.ws = TRUE, fixed=TRUE) {
  restore.point("cp_add_left_of")
  start = cp$start
  sstr = substring(cp$str, cp$start)

  left = left_of(sstr, left_of, fixed=fixed, not.found = rep(NA, length(sstr)))
  str_rows = which(!is.na(left))

  if (length(str_rows)==0) {
    cp$did_change = FALSE
    return(cp)
  }
  start = start[str_rows]
  left = left[str_rows]

  if (ignore.right.ws) {
    left = trimws(left, "right")
  }

  if (include_split) {
    left = paste0(left, left_of)
  }

  len = nchar(left)
  end = start+len-1
  cp = cp_add(cp, str_rows = str_rows, start=start, end=end, part=part, tag=tag, use_counter=use_counter)
  cp$did_change = TRUE

  cp
}

cp_jump_ws = function(cp) {
  sstr = substring(cp$str, cp$start)

  left_ws = nchar(sstr) - nchar(trimws(sstr,"left"))
  cp$start = cp$start + left_ws
  cp
}

```
# END OF FILE: /home/rstudio/repbox/repboxUtils/R/cmdpart_create.R

-----------------------------------------------------------


# FILE: /home/rstudio/repbox/repboxUtils/R/cmdpart_reg.R
```
# Create cmdpart representation of Stata regression commands

example = function() {
  cmdlines = c(
    "ivregress 2sls y1 x1 (y2 y3 = z1 z2), vce(robust)",
    "capt: xi: regress y i.i1##c.d1 [aw=x] if a == 5 in 3, vce(hc2)",
    #"capture quietly xi: regress y i.i1##c.d1, vce(hc2)",
    "capt: regress y i.i1##c.d1 if a==5 [aw=z], vce (robust)  opt2(arg2 = fun( funarg )) noarg"
  )
  options(warn=2)
  df = cmdparts_of_stata_reg(cmdlines)
}



cmdparts_of_stata_reg = function(cmdlines) {
  restore.point("stata_reg_cmdpart")

  if (length(cmdlines)==0) return(data.frame(str_row = integer(0), parent=character(0), part=character(0), content=character(0), tag=character(0), counter=integer(0), runid=integer(0)))

  str = trimws(cmdlines)
  # Replace tabs with spaces
  # Otherwise we wont correctly store the cmd
  # variable
  str = gsub("\t"," ", str, fixed=TRUE)


  # For some really tricky if conditions or similar
  # We first replace brackets and quotes by placeholders
  # reg y x1 if (i==1) | i==2 | inlist(f1, "A" "B") [aw=x1] in 5/25, robust   level( 95  )

  txt = paste0(str, collapse = "\n")
  pho = try(blocks.to.placeholder(txt, start=c("("), end=c(")"), ph.prefix = "#~br"))
  if (is(pho,"try-error")) {
    pho = stepwise.blocks.to.placeholder(str)
  }

  # In our example we have now
  # str = " if #~br1~# | i==2 | inlist#~br2~# [aw=x1] in 5/25 , robust"
  str = strsplit(pho$str,split = "\n")[[1]]
  if (length(str)==0) str = ""
  ph.df = pho$ph.df



  cp = cp_init(str)

  while(TRUE) {
    cp = cp_jump_ws(cp)
    cp = cp_add_starts_with(cp,c("quietly:","quiet:","qui:","quietly ","quiet ","qui ", "capture ","capture:","cap ", "cap:","capt ", "capt:"),"pre","cap_quiet",use_counter=TRUE)
    if (!cp$did_change) break
  }
  cp$str
  substring(cp$str, cp$start)

  # Find colon prefixes before command
  while(TRUE) {
    cp = cp_jump_ws(cp)
    cp = cp_add_left_of(cp,":","pre","",use_counter=TRUE, include_split=TRUE)
    if (!cp$did_change) break
  }

  cp$str
  substring(cp$str, cp$start)
  # Set brackets () into ph
  # res = set_cmdpart_block(str, cp, "(", ")","()","",counter=TRUE)
  # str = res$str; cp = res$cp

  cp = cp_jump_ws(cp)
  cp = cp_add_left_of(cp,"( )|(,)|$|(\\[)", "cmd", "",fixed = FALSE)



  cp = cp_jump_ws(cp)
  cp = cp_add_left_of(cp, "( in )|( if )|(\\[)|,|$", "varlist","", use_counter=FALSE, fixed=FALSE)



  # varlist ############################################

  # Pass the placeholder dictionary to cp so the sub-functions can resolve brackets
  cp$ph_df <- ph.df
  cp <- cmdpart_process_reg_varlists(cp)
  df = cp$df
  cp$str

  # weight_str, in_str and if_str #################################

  # Now it is getting a bit more complicated
  # We want to set if_str, in_str and weight_str
  # but they may appear in different orders or not at all

  # a) weight_str
  sub_start = cp$start
  sub_end = stri_locate_first_fixed(cp$str,",")[,1]-1
  sub_end = ifelse(is.na(sub_end),nchar(cp$str), sub_end )

  sstr = substring(cp$str, sub_start, sub_end)

  weight_start = stri_locate_first_fixed(sstr, "[")[,1] + sub_start -1
  weight_end = stri_locate_first_fixed(sstr, "]")[,2] + sub_start -1


  str_rows = which(!is.na(weight_start))

  if (length(str_rows)>0) {
    weight_str = substring(cp$str[str_rows], weight_start[str_rows], weight_end[str_rows])

    cp$str[str_rows] = stringi::stri_sub_replace(cp$str[str_rows], from=weight_start[str_rows], to=weight_end[str_rows], replacement="{{weight_str}}")



    equal_pos = stringi::stri_locate_first_fixed(weight_str,"=")[,1]
    has_weight_type = !is.na(equal_pos)
    weight_type = ifelse(has_weight_type,substring(weight_str,2, equal_pos-1) %>% trimws(), NA)
    var_start = ifelse(has_weight_type,equal_pos+1,2 )
    weight_var = substring(weight_str,var_start, nchar(weight_str)-1) %>% trimws()
    weight_str = ifelse(has_weight_type,
      paste0("[{{weight_type}}={{weight_var}}]"),
      paste0("[{{weight_var}}]")
    )

    n_add = NROW(weight_str)*3
    if (cp$n + n_add >= NROW(cp$df)) {
      cp$df = cp_add_empty_df(cp$df, n_add*2)
    }

    # 1a) add weight_str
    new.n = cp$n+length(weight_str)
    inds = (cp$n+1):new.n
    cp$df$parent[inds] = "main"
    cp$df$str_row[inds] = str_rows
    cp$df$part[inds] = "weight_str"
    cp$df$content[inds] = weight_str
    cp$n = new.n

    # 1b) Add weight_var
    new.n = cp$n+length(weight_str)
    inds = (cp$n+1):new.n
    cp$df$parent[inds] = "weight_str"
    cp$df$str_row[inds] = str_rows
    cp$df$part[inds] = "weight_var"
    cp$df$content[inds] = weight_var
    cp$n = new.n

    # 1c) Add weight_type
    new.n = cp$n+length(weight_str)
    inds = (cp$n+1):new.n
    cp$df$parent[inds] = "weight_type"
    cp$df$str_row[inds] = str_rows
    cp$df$part[inds] = "weight_type"
    cp$df$content[inds] = weight_type

    cp$n = new.n

  }

  # 2. if_str
  sub_end = stri_locate_first_fixed(cp$str,",")[,1]-1
  sub_end = ifelse(is.na(sub_end),nchar(cp$str), sub_end )
  sstr = substring(cp$str, sub_start, sub_end)

  if_start = stri_locate_first_fixed(sstr, " if ")[,1] + sub_start
  sstr = substring(sstr, if_start-sub_start+1)
  if_end = stri_locate_first_regex(sstr, "( in )|(\\{\\{)")[,1] + if_start - 2
  if_end = ifelse(is.na(if_end),sub_end, if_end)

  str_rows = which(!is.na(if_start))
  if_start = if_start[str_rows]; if_end = if_end[str_rows]
  cp = cp_add(cp,str_rows,if_start,if_end,"if_str","",ignore.right.ws=TRUE)

  cp$str

  # 3. in_str

  sub_end = stri_locate_first_fixed(cp$str,",")[,1]-1
  sub_end = ifelse(is.na(sub_end),nchar(cp$str), sub_end )
  sstr = substring(cp$str, sub_start, sub_end)

  in_start = stri_locate_first_fixed(sstr, " in ")[,1] + sub_start
  sstr = substring(sstr, in_start-sub_start+1)
  in_end = stri_locate_first_fixed(sstr, "{{")[,1] + in_start - 2
  in_end = ifelse(is.na(in_end),sub_end, in_end)

  str_rows = which(!is.na(in_start))
  in_start = in_start[str_rows]; in_end = in_end[str_rows]
  cp = cp_add(cp,str_rows,in_start,in_end,"in_str","",ignore.right.ws=TRUE)

  cp$str

  # options ###########################################

  # cp$str now looks e.g. like
  # {{cmd}} {{varlist}} {{if_str}} {{weight_str}} {{in_str}}, robust   level#~br3~#

  # We now replace bracket placeholders again since option parsing deals on its own with brackets
  restore.point("cmdpart_of_reg_opts")
  #options(warn=2)
  #disable.restore.points(!TRUE)
  #undebug(replace.placeholders)
  cp$str = replace.placeholders(cp$str, ph.df)
  cp$df$content = replace.ph.keep.lines(cp$df$content, ph.df)


  start = stri_locate_first_regex(cp$str,",")[,1]+1
  end = nchar(cp$str)
  str_rows = which(!is.na(start))

  make_opts = FALSE
  if (length(str_rows) > 0) {
    start = start[str_rows]; end = end[str_rows]
    all_opt_str = substring(cp$str[str_rows],start)
    res = cmdpart_parse_stata_opt_str(all_opt_str)
    lens = lapply(res$opt_str,length)
    make_opts = (any(lens>0))
  }
  if (make_opts) {
    # Replace str
    opt_ph = sapply(res$opt_str, function(x) paste0("{{opt_str", seq_along(x),"}}", collapse=" "))
    cp$str[str_rows] = stringi::stri_sub_replace(cp$str[str_rows], from=start, to=end, replacement=opt_ph)

    if (FALSE) {
      test_li = list(
        str_row = unlist(mapply(rep,x=str_rows, times=lens,SIMPLIFY = FALSE)),
        parent = "main",
        opt_str = unlist(res$opt_str),
        opt = unlist(res$opt),
        opt_arg = unlist(res$opt_arg)
      )
      sapply(test_li, length)
    }

    my_unlist = function(x, empty = character(0)) {
      res = unlist(x)
      if (is.null(res)) return(empty)
      res
    }

    opt_df = tibble(
        str_row = unlist(mapply(rep,x=str_rows, times=lens,SIMPLIFY = FALSE)),
        parent = rep("main", length(str_row)),
        opt_str = my_unlist(res$opt_str),
        opt = my_unlist(res$opt),
        opt_arg = my_unlist(res$opt_arg)
      ) %>%
      group_by(str_row) %>%
      mutate(opt_num = seq_len(n())) %>%
      ungroup()

    n_add = NROW(opt_df)*2 + sum(!is.na(opt_df$opt_arg))
    if (cp$n + n_add >= NROW(cp$df)) {
      cp$df = cp_add_empty_df(cp$df, n_add*2)
    }

    # 4a) add opt_str
    new.n = (cp$n+NROW(opt_df))
    inds = (cp$n+1):new.n
    cp$df$parent[inds] = "main"
    cp$df$str_row[inds] = opt_df$str_row
    cp$df$part[inds] = "opt_str"
    cp$df$counter[inds] = opt_df$opt_num
    cp$df$content[inds] = opt_df$opt_str

    cp$n = new.n

    # 4b) add opt
    new.n = (cp$n+NROW(opt_df))
    inds = (cp$n+1):new.n
    cp$df$parent[inds] = paste0("opt_str")
    cp$df$str_row[inds] = opt_df$str_row
    cp$df$part[inds] = "opt"
    cp$df$counter[inds] = opt_df$opt_num
    cp$df$content[inds] = opt_df$opt

    cp$n = new.n

    # 4c) add opt_arg where it exists
    rows = which(!is.na(opt_df$opt_arg))

    if (length(rows)>0) {
      new.n = cp$n+length(rows)
      inds = (cp$n+1):new.n
      cp$df$parent[inds] = "opt_str"
      cp$df$str_row[inds] = opt_df$str_row[rows]
      cp$df$part[inds] = "opt_arg"
      cp$df$counter[inds] = opt_df$opt_num[rows]
      cp$df$content[inds] = opt_df$opt_arg[rows]

      cp$n = new.n
    }

  }

  # adapt tags and df ##########################################

  df = cp$df[seq_len(cp$n),]
  rows = which(df$tag == "cap_quiet")
  if (length(rows)>0) {
    is_capture = has.substr(df$content[rows], "cap")
    df$tag[rows[is_capture]] = "capture"
    df$tag[rows[!is_capture]] = "quietly"
  }

  cont = trimws(df$content)
  rows = which(df$part == "pre")
  if (length(rows) > 0) {
    df$content[rows] = gsub("[ \t]+\\:",":", df$content[rows])
    irows = rows[trimws(df$content[rows]) == "xi:"]
    df$tag[irows] = "xi"
  }

  rows = which(df$part == "cmd" | df$part == "subcmd")
  df$tag[rows] = df$content[rows]

  df$content[seq_along(cp$str)] = cp$str


  restore.point("jslkfslfhksdfh")

  opt_rows = which(df$part == "opt" & df$content %in% c("vce","robust","cluster","r","ro","rob","robu","robus","cl","clu","clus","clust","cluste","cluster",""))
  df$tag[opt_rows] = "se"

  opt_str_rows = cmdpart_find_parent_rows(df, opt_rows)
  df$tag[opt_str_rows] = "se"

  opt_arg_rows = cmdpart_find_child_rows(df, opt_str_rows, "opt_arg") %>% na.omit()
  df$tag[opt_arg_rows] = "se"


  opt_rows = which(df$part == "opt" & df$content %in% c("absorb"))
  df$tag[opt_rows] = "absorb"

  opt_str_rows = cmdpart_find_parent_rows(df, opt_rows)
  df$tag[opt_str_rows] = "absorb"

  opt_arg_rows = cmdpart_find_child_rows(df, opt_str_rows, "opt_arg") %>% na.omit()
  df$tag[opt_arg_rows] = "absorb"


  df
}



#' Process all varlists in a cmdpart object
#'
#' This replaces the old loop in `cmdparts_of_stata_reg` that relied on the
#' legacy `parse.stata.reg.vars` function.
#' Extracts depvar, endo, exo, instr
#' Does NOT require dataset information (No column matching or glob expansion).
#'
#' @param cp The cmdpart object being built
#' @return The updated cmdpart object
cmdpart_process_reg_varlists = function(cp) {
  cmds = cp$df$content[cp$df$part == "cmd"]
  vl_rows = which(cp$df$part == "varlist")
  varlists = cp$df$content[vl_rows]

  for (i in seq_along(cmds)) {
    str_row = cp$df$str_row[vl_rows[i]]
    cmd = cmds[i]
    varlist_str = varlists[i]

    # Replace bracket placeholders if they were swapped out earlier
    if (!is.null(cp$ph_df)) {
      varlist_str = replace.placeholders(varlist_str, cp$ph_df)
    }

    # 1. Syntactic parsing of the varlist string into tokens
    tokens_df = cmdpart_parse_varlist(cmd, varlist_str)
    if (is.null(tokens_df) || nrow(tokens_df) == 0) next

    # 2. Extract and handle subcmd (e.g., '2sls' in 'ivregress 2sls')
    subcmd_row = tokens_df[tokens_df$part == "subcmd", ]
    if (nrow(subcmd_row) > 0) {
      # Adjust the original string to include the subcmd placeholder
      cp$str[str_row] = gsub("{{varlist}}", "{{subcmd}} {{varlist}}", cp$str[str_row], fixed = TRUE)
      cp$start[str_row] = cp$start[str_row] + nchar("{{subcmd}} ")

      # Register the subcmd in the cmdpart df
      cp = cp_add_part_in_df(cp, str_rows = str_row, part = "subcmd", content = subcmd_row$content)
    }

    # 3. Register the variable tokens
    v_rows = tokens_df[tokens_df$part == "v", ]
    if (nrow(v_rows) > 0) {
      cp = cp_add_part_in_df(
        cp,
        str_rows = str_row,
        part = "v",
        content = v_rows$content,
        tag = v_rows$tag,
        counter = seq_len(nrow(v_rows)),
        parent = "varlist"
      )

      # 4. Reconstruct the {{varlist}} content string with placeholders
      dep_ph = "{{v1}}"

      exo_idx = which(v_rows$tag == "exo")
      exo_ph = if (length(exo_idx) > 0) paste0("{{v", exo_idx, "}}", collapse = " ") else ""

      endo_idx = which(v_rows$tag == "endo")
      endo_ph = if (length(endo_idx) > 0) paste0("{{v", endo_idx, "}}", collapse = " ") else ""

      instr_idx = which(v_rows$tag == "instr")
      instr_ph = if (length(instr_idx) > 0) paste0("{{v", instr_idx, "}}", collapse = " ") else ""

      # Build the new string preserving IV parenthesis structure
      if (length(endo_idx) == 0 && length(instr_idx) == 0) {
        new_content = paste(c(dep_ph, if (nchar(exo_ph) > 0) exo_ph else NULL), collapse = " ")
      } else {
        new_content = paste0(
          dep_ph,
          if (nchar(exo_ph) > 0) paste0(" ", exo_ph) else "",
          " (", endo_ph, " = ", instr_ph, ")"
        )
      }

      cp$df$content[vl_rows[i]] = trimws(new_content)
    }
  }

  return(cp)
}

#' Parse a Stata varlist syntactically based on the command type
cmdpart_parse_varlist = function(cmd, varlist_str) {
  varlist_str = trimws(varlist_str)

  # Normalize spaces around dashes to keep ranges (e.g., "var1 - var5") as a single token
  varlist_str = gsub("\\s*-\\s*", "-", varlist_str)

  iv_commands = c("ivregress", "ivreg2", "ivreg", "xtivreg2", "xtivreg", "ivreghdfe")
  is_iv_cmd = cmd %in% iv_commands
  is_reghdfe = cmd == "reghdfe"

  # Check if there is an explicit Instrumental Variable block: (endo = instr)
  has_iv_syntax = grepl("\\(.*=.*\\)", varlist_str)

  if ((is_iv_cmd || is_reghdfe) && has_iv_syntax) {
    return(cmdpart_parse_iv_varlist(cmd, varlist_str))
  } else {
    return(cmdpart_parse_default_varlist(varlist_str))
  }
}

#' Parse standard OLS varlists
cmdpart_parse_default_varlist = function(varlist_str) {
  # Collapse multiple spaces and tokenize
  varlist_str = gsub("\\s+", " ", varlist_str)
  tokens = strsplit(varlist_str, " ")[[1]]
  tokens = tokens[tokens != ""]

  if (length(tokens) == 0) return(NULL)

  depvar = tokens[1]
  exo = if (length(tokens) > 1) tokens[2:length(tokens)] else character(0)

  df = tibble::tibble(
    part = "v",
    tag = c("depvar", rep("exo", length(exo))),
    content = c(depvar, exo),
    parent = "varlist"
  )
  return(df)
}

#' Parse IV varlists including subcommands and parenthesis blocks
cmdpart_parse_iv_varlist = function(cmd, varlist_str) {
  subcmd = NULL

  # Extract specific subcmd for `ivregress` (e.g., "2sls", "gmm")
  if (cmd == "ivregress") {
    parts = strsplit(varlist_str, "\\s+", perl = TRUE)[[1]]
    subcmd = parts[1]
    # Strip subcmd from the beginning of the varlist
    varlist_str = sub(paste0("^", subcmd, "\\s+"), "", varlist_str)
    varlist_str = trimws(varlist_str)
  }

  # Locate the (endo = instr) block
  br_start = regexpr("\\(", varlist_str)
  br_end = regexpr("\\)", varlist_str)

  if (br_start > 0 && br_end > br_start) {
    iv_block = substr(varlist_str, br_start + 1, br_end - 1)

    # Everything outside the parentheses are either the depvar or exogenous variables
    outside_before = trimws(substr(varlist_str, 1, br_start - 1))
    outside_after = trimws(substr(varlist_str, br_end + 1, nchar(varlist_str)))
    outside_str = trimws(paste(outside_before, outside_after))

    # Parse IV block
    eq_pos = regexpr("=", iv_block)
    if (eq_pos > 0) {
      endo_str = trimws(substr(iv_block, 1, eq_pos - 1))
      instr_str = trimws(substr(iv_block, eq_pos + 1, nchar(iv_block)))

      endo = strsplit(gsub("\\s+", " ", endo_str), " ")[[1]]
      instr = strsplit(gsub("\\s+", " ", instr_str), " ")[[1]]

      endo = endo[endo != ""]
      instr = instr[instr != ""]
    } else {
      # Fallback if '=' is missing inside parenthesis
      endo = character(0)
      instr = strsplit(gsub("\\s+", " ", iv_block), " ")[[1]]
      instr = instr[instr != ""]
    }

    # Parse Outside block
    outside_tokens = strsplit(gsub("\\s+", " ", outside_str), " ")[[1]]
    outside_tokens = outside_tokens[outside_tokens != ""]

    depvar = outside_tokens[1]
    exo = if (length(outside_tokens) > 1) outside_tokens[2:length(outside_tokens)] else character(0)

  } else {
    # Fallback to standard OLS parsing if IV regex logic fails
    return(cmdpart_parse_default_varlist(varlist_str))
  }

  # Construct token dataframe
  df = tibble::tibble(
    part = c(if (!is.null(subcmd)) "subcmd" else character(0),
             rep("v", 1 + length(exo) + length(endo) + length(instr))),
    tag = c(if (!is.null(subcmd)) "" else character(0),
            "depvar",
            rep("exo", length(exo)),
            rep("endo", length(endo)),
            rep("instr", length(instr))),
    content = c(if (!is.null(subcmd)) subcmd else character(0),
                depvar, exo, endo, instr),
    parent = c(if (!is.null(subcmd)) "varlist" else character(0),
               rep("varlist", 1 + length(exo) + length(endo) + length(instr)))
  )

  return(df)
}
```
# END OF FILE: /home/rstudio/repbox/repboxUtils/R/cmdpart_reg.R

-----------------------------------------------------------


# FILE: /home/rstudio/repbox/repboxUtils/R/cmdpart_tests.R
```
# FILE: cmdpart_test.R

# Tests for the pure syntactic cmdpart Stata regression parser.

example = function() {
  cmdpart_unit_tests()
}

#' Run the test suite for syntactic Stata regression parsing
cmdpart_unit_tests <- function() {


  # Non-trivial Stata regression commands to test syntactic parsing
  test_cmds <- c(
    # 1. Basic OLS with if (containing parentheses), in, weights, and options
    "regress y x1 x2 if (age > 18) | (income == 500) [aw=weight_var] in 1/100, robust cluster(id)",

    # 2. IV regression with subcmd, exogenous vars, and cluster option
    "ivregress 2sls y x1 x2 (endo1 endo2 = instr1 instr2 instr3) if valid == 1, vce(cluster state)",

    # 3. High-dimensional FE with wildcards, ranges, and multiple options
    "quietly xi: reghdfe y x1-x5 i.year* i.region#c.income, absorb(id year) vce(hc1)",

    # 4. IV regression without subcmd, no exogenous variables, and probability weights
    "ivreg2 y (x1 = z1 z2 z3)[pw=prob_wt], cluster(county)"
  )

  cat("Running cmdpart syntactic parsing tests...\n")

  # Parse all commands at once using the refactored function
  # (Assumes cmdparts_of_stata_reg and cmdpart_regvar.R functions are loaded)
  parsed_df <- cmdparts_of_stata_reg(test_cmds)

  # Helper function to extract specific tokens for a given string index
  get_tokens <- function(df, str_idx, part_name, tag_name = NULL) {
    sub_df <- df[df$str_row == str_idx & df$part == part_name, ]
    if (!is.null(tag_name)) {
      sub_df <- sub_df[sub_df$tag == tag_name, ]
    }
    return(sub_df$content)
  }

  # -------------------------------------------------------------------------
  # Test Case 1: regress y x1 x2 if (age > 18) | (income == 500)[aw=weight_var] in 1/100, robust cluster(id)
  # -------------------------------------------------------------------------
  cat("  Testing Case 1 (OLS + if/in/weights)...\n")
  stopifnot(get_tokens(parsed_df, 1, "cmd") == "regress")
  stopifnot(get_tokens(parsed_df, 1, "v", "depvar") == "y")
  stopifnot(identical(get_tokens(parsed_df, 1, "v", "exo"), c("x1", "x2")))
  stopifnot(get_tokens(parsed_df, 1, "if_str") == "if (age > 18) | (income == 500)")
  stopifnot(get_tokens(parsed_df, 1, "in_str") == "in 1/100")
  stopifnot(get_tokens(parsed_df, 1, "weight_var") == "weight_var")
  stopifnot(get_tokens(parsed_df, 1, "weight_type") == "aw")

  opt_args <- get_tokens(parsed_df, 1, "opt_arg")
  opts <- get_tokens(parsed_df, 1, "opt")
  opts
  stopifnot("robust" %in% opts)
  stopifnot("cluster" %in% opts && opt_args[1] == "id")

  # -------------------------------------------------------------------------
  # Test Case 2: ivregress 2sls y x1 x2 (endo1 endo2 = instr1 instr2 instr3) if valid == 1, vce(cluster state)
  # -------------------------------------------------------------------------
  cat("  Testing Case 2 (ivregress with subcmd)...\n")
  stopifnot(get_tokens(parsed_df, 2, "cmd") == "ivregress")
  stopifnot(get_tokens(parsed_df, 2, "subcmd") == "2sls")
  stopifnot(get_tokens(parsed_df, 2, "v", "depvar") == "y")
  stopifnot(identical(get_tokens(parsed_df, 2, "v", "exo"), c("x1", "x2")))
  stopifnot(identical(get_tokens(parsed_df, 2, "v", "endo"), c("endo1", "endo2")))
  stopifnot(identical(get_tokens(parsed_df, 2, "v", "instr"), c("instr1", "instr2", "instr3")))
  stopifnot(get_tokens(parsed_df, 2, "if_str") == "if valid == 1")

  opts <- get_tokens(parsed_df, 2, "opt")
  opt_args <- get_tokens(parsed_df, 2, "opt_arg")
  stopifnot("vce" %in% opts && opt_args[opts == "vce"] == "cluster state")

  # -------------------------------------------------------------------------
  # Test Case 3: quietly xi: reghdfe y x1-x5 i.year* i.region#c.income, absorb(id year) vce(hc1)
  # -------------------------------------------------------------------------
  cat("  Testing Case 3 (reghdfe with prefixes, globs, ranges)...\n")

  # Check prefixes (quietly, xi)

  pre_tags <- parsed_df$tag[parsed_df$str_row == 3 & parsed_df$part == "pre"]
  stopifnot("quietly" %in% pre_tags && "xi" %in% pre_tags)
  parsed_df[parsed_df$str_row == 3 & parsed_df$part == "pre",]

  stopifnot(get_tokens(parsed_df, 3, "cmd") == "reghdfe")
  stopifnot(get_tokens(parsed_df, 3, "v", "depvar") == "y")

  # Ensure globs and ranges are retained natively (no data resolution needed yet)
  exo_vars <- get_tokens(parsed_df, 3, "v", "exo")
  stopifnot(identical(exo_vars, c("x1-x5", "i.year*", "i.region#c.income")))

  opts <- get_tokens(parsed_df, 3, "opt")
  opt_args <- get_tokens(parsed_df, 3, "opt_arg")
  stopifnot("absorb" %in% opts && opt_args[opts == "absorb"] == "id year")
  stopifnot("vce" %in% opts && opt_args[opts == "vce"] == "hc1")

  # -------------------------------------------------------------------------
  # Test Case 4: ivreg2 y (x1 = z1 z2 z3) [pw=prob_wt], cluster(county)
  # -------------------------------------------------------------------------
  cat("  Testing Case 4 (ivreg2 without subcmd, pure IV)...\n")
  stopifnot(get_tokens(parsed_df, 4, "cmd") == "ivreg2")
  stopifnot(length(get_tokens(parsed_df, 4, "subcmd")) == 0) # No subcmd expected
  stopifnot(get_tokens(parsed_df, 4, "v", "depvar") == "y")

  # Should have 0 exogenous variables
  stopifnot(length(get_tokens(parsed_df, 4, "v", "exo")) == 0)

  stopifnot(get_tokens(parsed_df, 4, "v", "endo") == "x1")
  stopifnot(identical(get_tokens(parsed_df, 4, "v", "instr"), c("z1", "z2", "z3")))

  stopifnot(get_tokens(parsed_df, 4, "weight_var") == "prob_wt")
  stopifnot(get_tokens(parsed_df, 4, "weight_type") == "pw")

  opts <- get_tokens(parsed_df, 4, "opt")
  opt_args <- get_tokens(parsed_df, 4, "opt_arg")
  stopifnot("cluster" %in% opts && opt_args[opts == "cluster"] == "county")

  cat("\nAll syntactic cmdpart tests passed successfully! Phase 1 logic is sound.\n")
}
```
# END OF FILE: /home/rstudio/repbox/repboxUtils/R/cmdpart_tests.R

-----------------------------------------------------------


# FILE: /home/rstudio/repbox/repboxUtils/R/cmdpart_use.R
```
# Tools for working with command part representations
# or wrappers that use them under the hood.

cmdpart_parse_stata_opt_str = function(str) {
  restore.point("cmdpart_of_stata_opt_str")

  # str = c(
  #   "vce (robust)  opt2(arg2 = fun( funarg )) noarg",
  #   "absorb(x) robust"
  # )


  # We have examples like absorb(var)r
  # we need to transform it to absorb(var) r
  str = stri_replace_all_regex(str,"\\)(?=[a-zA-Z])",") ")


  all_opt_str = all_opt = all_opt_arg = vector("list",NROW(str))


  i = 221
  for (i in seq_along(str)) {
    s = str[i]
    if (trimws(s)=="") next

    # 1. Find 1st level braces and replace with ph
    brace_pos = locate_1st_level_braces(s,open="(",close=")")

    if (NROW(brace_pos)==0) {
      s = shorten.spaces(s) %>% trimws()
      all_opt[[i]] = strsplit(s, " ", fixed=TRUE)[[1]]
      all_opt_str[[i]] = paste0("{{opt", seq_along(all_opt[[i]]),"}}")
      all_opt_arg[[i]] = rep(NA, length(all_opt[[i]]))
      next
    }

    # 1. Replace 1st level braces with placeholders
    brace_content = substring(s, brace_pos[,1], brace_pos[,2])
    ph = paste0("#~(", seq_len(NROW(brace_pos)),"~#")
    s = str.replace.at.pos(s, brace_pos, ph)

    # 2. Remove all ws before "#~()~#" and shorten ws
    s = gsub("[ \t]+#~\\(","#~(", s)
    s = shorten.spaces(s) %>% trimws()

    # 3. Split by " "
    opt_str = strsplit(s," ", fixed=TRUE)[[1]]

    # 4. locate argument placeholders
    arg_start_pos = stringi::stri_locate_first_fixed(opt_str, "#~(")[,1]
    has_arg = !is.na(arg_start_pos)

    opt_arg = rep(NA, length(opt_str))
    opt_arg[has_arg] = str.remove.ends(brace_content,1,1)

    opt = ifelse(has_arg,substring(opt_str,1, arg_start_pos-1), opt_str)

    all_opt_str[[i]] = opt_str
    all_opt[[i]] = opt
    all_opt_arg[[i]] = opt_arg

    all_opt_str[[i]] = ifelse(has_arg,
      paste0("{{opt", seq_along(opt),"}}({{opt_arg",seq_along(opt),"}})"),
      paste0("{{opt", seq_along(opt),"}}")
    )

  }
  list(
    opt_str = all_opt_str,
    opt = all_opt,
    opt_arg = all_opt_arg
  )
}

cmdpart_get_placeholders = function(cp_df, prefix="{{", postfix="}}") {
  ifelse(is.true(cp_df$counter > 0),
    paste0(prefix, cp_df$part, cp_df$counter, postfix),
    paste0(prefix, cp_df$part, postfix)
  )
}

cmdpart_create_cmdline = function(cp_df) {

  main_row = which(cp_df$part == "main")
  str = cp_df$content[main_row]
  ph = cmdpart_get_placeholders(cp_df)

  # while(TRUE) {
  #   str_n = stri_replace_all_fixed(str, ph, cp_df$content, vectorize_all = FALSE)
  #   if (str_n == str) break
  #   str = str_n
  # }
  stri_replace_all_fixed(str, ph, cp_df$content, vectorize_all = FALSE)

}

cmdpart_find_parent_rows = function(df, rows=seq_along(NROW(df)), remove.na=FALSE) {
  if ("str_row" %in% colnames(df)) {
    part.key = paste0(df$str_row,"|", df$part ,"|",df$counter)
    parent.key = paste0(df$str_row,"|", df$parent,"|",df$counter)
  } else if ("artid" %in% colnames(df)) {
    part.key = paste0(df$artid,"|", df$step, "|", df$part,"|",df$counter)
    parent.key = paste0(df$artid,"|", df$step, "|", df$parent,"|",df$counter)
  } else {
    part.key = paste0(df$step, "|", df$part,"|",df$counter)
    parent.key = paste0(df$step, "|", df$parent,"|",df$counter)
  }
  match(parent.key[rows], part.key)
}

cmdpart_find_child_rows = function(df, rows=seq_along(NROW(df)), child_part) {
  if ("str_row" %in% colnames(df)) {
    part.key = paste0(df$str_row,"|", df$part,"|",df$counter)
    parent.key = paste0(df$str_row,"|", df$parent,"|",df$counter)
  } else if ("artid" %in% colnames(df)) {
    part.key = paste0(df$artid,"|", df$step, "|", df$part,"|",df$counter)
    parent.key = paste0(df$artid,"|", df$step, "|", df$parent,"|",df$counter)
  } else {
    part.key = paste0(df$step, "|", df$part,"|",df$counter)
    parent.key = paste0(df$step, "|", df$parent,"|",df$counter)
  }
  parent.key[df$part != child_part] = NA

  match(part.key[rows], parent.key)

}


example = function() {
  cmdpart = readRDS("C:/libraries/repbox/projects_reg/testsupp/repdb/cmdpart.Rds")$cmdpart
  cmdpart_to_opts_df(cmdpart)
}

cmdpart_to_opts_df = function(cmdpart) {
  restore.point("cmdpart_to_opts_df")


  opt_df = filter(cmdpart, part=="opt") %>% select(runid, counter, opt=content, tag=tag)
  opt_arg = filter(cmdpart, part=="opt_arg") %>% select(runid, counter, opt_arg=content)
  left_join(opt_df, opt_arg, by=c("runid","counter"))
}



locate_1st_level_braces = function(txt, open="(", close = ")") {
  #restore.point("locate_1st_level_braces")
  if (length(txt)==0) return(NULL)
  res = try(str.blocks.pos(txt, open, close), silent=TRUE)
  if (is(res,"try-error")) {
    cat("\nNon-matching braces in reg options:\n  ", txt)
    return(NULL)
  }
  res$outer[res$levels==1,,drop=FALSE]
}


```
# END OF FILE: /home/rstudio/repbox/repboxUtils/R/cmdpart_use.R

-----------------------------------------------------------


# FILE: /home/rstudio/repbox/repboxUtils/R/detach_all_pkg.R
```
example = function() {
  detach_all_packages()
}
detach_all_packages = function(which = loadedNamespaces(), except = c("base","stats","graphics")) {
  stop("Don't run: does not nicely work yet.")
  loaded_packages <- setdiff(which,except)

  for (i in 1:10) {
    # Loop over each package and detach it
    for (pkg in loaded_packages) {
      suppressWarnings(try(detach(paste0("package:", pkg), character.only = TRUE, unload = TRUE), silent = TRUE))
    }
  }
  loadedNamespaces()
}
```
# END OF FILE: /home/rstudio/repbox/repboxUtils/R/detach_all_pkg.R

-----------------------------------------------------------


# FILE: /home/rstudio/repbox/repboxUtils/R/encoding.R
```
guess_encoding_and_read_text <- function(file_path,
                                         default_guess = "UTF-8",
                                         only_allow = c("UTF*"),
                                         raw_data = NULL) {
  # If raw_data is not already provided, read it from the file
  if (is.null(raw_data)) {
    raw_data <- readBin(file_path, what = "raw", n = file.info(file_path)$size)
  }
  
  # Detect encodings using stringi
  enc_info_list <- stri_enc_detect(raw_data)
  
  # If there are no guesses at all, fall back immediately
  if (length(enc_info_list) == 0 || nrow(enc_info_list[[1]]) == 0) {
    warning(sprintf("No encoding guess could be made. Defaulting to '%s'.", default_guess))
    best_enc <- default_guess
  } else {
    enc_info <- enc_info_list[[1]]  # data frame with "Encoding" and "Confidence"
    
    # Filter encodings only if `only_allow` is not NULL
    if (!is.null(only_allow)) {
      # Convert each element of only_allow to a regex via glob2rx()
      keep_rows <- lapply(only_allow, function(p) {
        grep(glob2rx(p), enc_info$Encoding, ignore.case = TRUE)
      })
      keep_rows <- unique(unlist(keep_rows))
      
      enc_info_filtered <- enc_info[keep_rows, ]
      
      if (nrow(enc_info_filtered) == 0) {
        warning(sprintf(
          "No encodings matched patterns: %s. Defaulting to '%s'.", 
          paste(only_allow, collapse=", "), default_guess
        ))
        best_enc <- default_guess
      } else {
        best_row <- which.max(enc_info_filtered$Confidence)
        best_enc <- enc_info_filtered$Encoding[best_row]
      }
    } else {
      # only_allow is NULL -> allow any encodings
      best_row <- which.max(enc_info$Confidence)
      best_enc <- enc_info$Encoding[best_row]
    }
  }
  
  # Convert the raw bytes to text (best_enc -> UTF-8)
  text_content <- stri_encode(raw_data, from = best_enc, to = "UTF-8")
  
  # Return a list with raw data, text, and final guessed encoding
  list(
    raw              = raw_data,
    text             = text_content,
    guessed_encoding = best_enc
  )
}


guess_encoding_and_read_html <- function(file_path, 
                                         default_guess = "UTF-8", 
                                         only_allow = c("UTF*")) {
  restore.point("guess_encoding_and_read_html")
  library(xml2)
  # (A) Read raw bytes once
  raw_data <- readBin(file_path, what = "raw", n = file.info(file_path)$size)
  
  # (B) Decode as UTF-8 (the "initial assumption") and parse HTML
  text_default <- stringi::stri_encode(raw_data, from = "UTF-8", to = "UTF-8")
  
  # # Handle any decoding errors gracefully by ignoring invalid bytes:
  # text_default <- stringi::stri_encode(raw_data, from = "UTF-8", to = "UTF-8", 
  #                                       to_raw = FALSE, 
  #                                       ignore_errors = TRUE)
  
  doc <- tryCatch(
    read_html(text_default),
    error = function(e) {
      # If decoding as UTF-8 fails badly, fall back to guess_encoding_and_read_text
      message("Failed to parse as UTF-8: ", e$message)
      return(NULL)
    }
  )
  
  # If we couldn't parse it at all, skip meta detection
  if (is.null(doc)) {
    # fallback: guess
    guessed <- guess_encoding_and_read_text(file_path, default_guess, only_allow, raw_data)
    doc <- read_html(guessed$text)
    return(list(
      doc              = doc,
      text             = guessed$text,
      guessed_encoding = guessed$guessed_encoding
    ))
  }
  
  # (C) Check for meta charset
  # First, try:  <meta charset="...">
  meta_node <- xml_find_first(doc, "//meta[@charset]")
  meta_charset <- NA_character_
  if (!inherits(meta_node, "xml_missing") && !is.na(meta_node)) {
    meta_charset <- xml_attr(meta_node, "charset")
  }
  
  # If not found, try: <meta http-equiv="Content-Type" content="text/html; charset=...">
  if (is.na(meta_charset) || meta_charset == "") {
    meta_node_2 <- xml_find_first(doc, "//meta[@http-equiv='Content-Type'][contains(@content, 'charset=')]")
    if (!inherits(meta_node_2, "xml_missing") && !is.na(meta_node_2)) {
      content_val <- xml_attr(meta_node_2, "content")
      # parse out "charset=..."
      # e.g. content="text/html; charset=ISO-8859-1"
      meta_charset <- sub(".*charset=([^;]+).*", "\\1", content_val, ignore.case = TRUE)
    }
  }
  
  # (D) If we found a declared encoding in the meta tag, re-decode using that
  if (!is.na(meta_charset) && meta_charset != "") {
    # Re-decode raw data with meta_charset -> UTF-8
    new_text <- tryCatch(
      stringi::stri_encode(raw_data, from = meta_charset, to = "UTF-8"),
      error = function(e) {
        message(sprintf("Failed to decode using meta charset '%s': %s", meta_charset, e$message))
        return(NULL)
      }
    )
    
    if (is.null(new_text)) {
      # If decoding with meta_charset fails, fallback to guess_encoding
      guessed <- guess_encoding_and_read_text(file_path, default_guess, only_allow, raw_data)
      final_doc <- read_html(guessed$text)
      return(list(
        doc              = final_doc,
        text             = guessed$text,
        guessed_encoding = guessed$guessed_encoding
      ))
    } else {
      # Successfully re-decoded the data -> parse it
      final_doc <- read_html(new_text)
      return(list(
        doc              = final_doc,
        text             = new_text,
        guessed_encoding = meta_charset
      ))
    }
  } else {
    # (E) No meta charset found -> fallback to heuristics
    guessed <- guess_encoding_and_read_text(file_path, default_guess, only_allow, raw_data)
    final_doc <- read_html(guessed$text)
    return(list(
      doc              = final_doc,
      text             = guessed$text,
      guessed_encoding = guessed$guessed_encoding
    ))
  }
}

```
# END OF FILE: /home/rstudio/repbox/repboxUtils/R/encoding.R

-----------------------------------------------------------


# FILE: /home/rstudio/repbox/repboxUtils/R/encrypted_7z.R
```
extract_all_zip = function(dir) {
  zips = list.files(dir, glob2rx("*.zip"), full.names = TRUE, ignore.case = TRUE)
  if (length(zips)>0) {
    for (zip in zips) {
      unzip(zipfile = zip, exdir=dir)
    }
  }
  
}

extract_all_encrypted_7z = function(dir) {
  # Extract possibly compressed article PDF
  key = Sys.getenv("ENCRYPT_KEY")
  #print(paste0("Key = ", key))
  zips = list.files(dir, glob2rx("*.7z"), full.names = TRUE)
  if (length(zips)>0) {
    for (zip in zips) {
      extract.7z(dir, zip = zip, password = key)
    }
  }
}



to.7z = function(path, zip=paste0(basename(path),".7z"), password = NULL) {
  switch = ""
  if (!is.null(password)) {
    switch = paste0(" -p",password," ")
  }
  os =
  cmd = paste0('7z a ', zip, ' ', path,' ',  switch)
  cat(cmd)
  system(cmd)
}

extract.7z = function(path, zip=paste0(basename(path),".7z"), password = NULL) {
  setwd(path)
  switch = ""
  if (!is.null(password)) {
    switch = paste0(" -p",password," ")
  }
  cmd = paste0('7z x ', zip, ' -y ',  switch)
  cat("\n", cmd,"\n")
  system(cmd,ignore.stdout = TRUE)
}


to.7z = function(path, zip=paste0(basename(path),".7z"), password = NULL) {
  switch = ""
  if (!is.null(password)) {
    switch = paste0(" -p",password," ")
  }
  cmd = paste0('7z a ', zip, ' ', path,' ',  switch)
  cat(cmd)
  system(cmd)
}
```
# END OF FILE: /home/rstudio/repbox/repboxUtils/R/encrypted_7z.R

-----------------------------------------------------------


# FILE: /home/rstudio/repbox/repboxUtils/R/problems.R
```
repbox_set_problem_options = function(project_dir=NULL, fail_action="error", metaid=NA_character_, forced_fail_action = NULL) {
  options(repbox.problem.options = list(project_dir=project_dir, fail_action=fail_action, metaid=metaid, forced_fail_action=forced_fail_action))
}

repbox_problem_opts = function(project_dir, fail_action="error") {
  getOption("repbox.problem.options")
}

repbox_runid_problems = function() {
  getOption("repbox.runid.problems")
}

repbox_problem_set_runid = function(runid=NA_integer_) {
  options(repbox.problem.runid = runid)
  if (!is.na(runid)) {
    options(repbox.runid.problems = list())
  }
}

repbox_problem_get_runid = function() {
  runid = getOption("repbox.problem.runid")
  if (is.null(runid)) runid = NA_integer_
  runid
}




#' A function that deals with failures depending on the on_fail action
make_fail_fun = function(fail_action) {
  if (fail_action=="error") {
    fail_fun = function(...) stop(paste0(...),call. = FALSE)
  } else if (fail_action=="warn") {
    fail_fun = function(...) warning(paste0(...), call. = FALSE)
  } else if (fail_action=="msg") {
    fail_fun = function(...) cat(paste0("\n",...,"\n"))
  } else {
    fail_fun = function(...) {}
  }
  fail_fun
}

repbox_set_current_project_dir = function(project_dir) {
  options(repbox.current.project.dir = project_dir)
}

repbox_get_current_project_dir = function() {
  getOption("repbox.current.project.dir")
}

#' A function that deals with failures depending on the on_fail action
repbox_problem = function(msg, type, fail_action=opts$fail_action, project_dir=opts$project_dir,  extra=list(),metaid=opts$metaid, runid=repbox_problem_get_runid(), opts=repbox_problem_opts()) {
  restore.point("repbox_problem")


  if (!is.null(opts$forced_fail_action)) {
    fail_action = opts$forced_fail_action
  }


  type = make_valid_filename(type)
  if (is.null(project_dir)) {
    stop("project_dir not specfied")
  }
  prob = list(type=type,msg=msg, metaid=metaid, runid=runid, extra=extra)

  hash = digest::digest(prob)

  prob$hash = hash
  prob$time = Sys.time()
  if (is.null(metaid)) metaid = NA
  if (is.na(metaid) | isTRUE(metaid %in% c("base"))) {
    problem_dir = file.path(project_dir,"problems")
  } else {
    problem_dir = file.path(project_dir,"metareg", metaid, "problems")
  }

  if (!dir.exists(problem_dir)) dir.create(problem_dir,recursive = TRUE)

  short_hash = substr(hash, 1,8)
  if (is.na(runid)) {
    #num_files = length(list.files(problem_dir))
    #prob_num = num_files +1
    saveRDS(prob, paste0(problem_dir,"/problem_", type,"__", short_hash, ".Rds"))
  } else {
    saveRDS(prob, paste0(problem_dir,"/runid_problem_", runid,"__", type,"__", short_hash, ".Rds"))
  }

  if (!is.na(runid)) {
    runid_problems = getOption("repbox.runid.problems")
    if (is.null(runid_problems)) {
      runid_problems = list(prob)
    } else {
      runid_problems = c(runid_problems, list(prob))
    }
    options(repbox.runid.problems = runid_problems)
  }

  if (fail_action=="error") {
    stop(msg,call. = FALSE)
  } else if (fail_action=="warn") {
    warning(msg, call. = FALSE)
  } else if (fail_action=="msg") {
    cat(paste0("\n",msg,"\n"))
  }
  invisible(prob)
}


try_catch_repbox_problems <- function(expr,project_dir, warn_action="msg", err_action="msg", runid=NULL, msg_prefix="", err_val=NULL) {
  warn_li = list()
  err <- NULL
  value <- withCallingHandlers(
    tryCatch(expr, error=function(e) {
      err <<- paste0(as.character(e), collapse="\n")#captureOutput(print(e))#
      NULL
    }), warning=function(w) {
      warn_li[[length(warn_li)+1]] <<- captureOutput(print(w), collapse="\n")#as.character(w)
      invokeRestart("muffleWarning")
    })

  if (!is.null(err)) {
    value = err_val
    repbox_problem(paste0(msg_prefix,err),"error", fail_action=err_action, project_dir=project_dir, runid=runid)
  }
  for (w in warn_li) {
    repbox_problem(paste0(msg_prefix,w),"warning", fail_action=warn_action, project_dir=project_dir, runid=runid)
  }

  list(value=value, warnings=warn_li, error=err, has_err = !is.null(err))
}


tryCatchWarningsAndError <- function(expr) {
  warn_li = list()
  err <- NULL
  value <- withCallingHandlers(
    tryCatch(expr, error=function(e) {
      err <<- e
      NULL
    }), warning=function(w) {
      warn_li[[length(warn_li)+1]] <<- w
      invokeRestart("muffleWarning")
    })
  list(value=value, warnings=warn_li, error=err)
}
```
# END OF FILE: /home/rstudio/repbox/repboxUtils/R/problems.R

-----------------------------------------------------------


# FILE: /home/rstudio/repbox/repboxUtils/R/tools.R
```
example = function() {
  make_valid_filename("dh(5/sdh.txt")
}

is_empty_str = function(x) {
  is.na(x) | is.true(x=="")
}

write_utf8 <- function(x, file, bom=F) {
  x = paste0(x, collapse="\n")
  con <- file(file, "wb")
  if(bom) writeBin(BOM, con, endian="little")
  writeBin(charToRaw(x), con, endian="little")
  close(con)
}

#' Read a text file that was saved in UTF-8 format
#' @export
read_utf8 <- function(file,sep.lines=FALSE,warn=FALSE,...) {
  text <- readLines(file,encoding = "UTF-8",warn=warn,...)
  if (!sep.lines) text = paste0(text, collapse="\n")
  text
}

#' Read an RDS file if it exists. Otherwise return NULL
#' @export
read_rds_or_null = function (file) {
    if (!file.exists(file))
        return(NULL)
    readRDS(file)
}

#' Saves an RDS file and creates directory of missing
#' @export
save_rds_create_dir = function(x, file) {
  dir = dirname(file)
  if (!dir.exists(dir)) dir.create(dir, recursive = TRUE)
  saveRDS(x, file)
}

copy_into_list <- function(source = parent.frame(), dest = list(), exclude = NULL) {
  # Get all objects in the source environment
  all_vars <- ls(envir = source, all.names = TRUE)

  # Filter out variables to exclude
  if (length(exclude)>0) {
    vars_to_copy <- setdiff(all_vars, exclude)
  } else {
    vars_to_copy <- all_vars
  }

  # Vectorized assignment using mget() to get multiple objects at once
  if (length(vars_to_copy) > 0) {
    values <- mget(vars_to_copy, envir = source)
    dest[names(values)] <- values
  }

  # Return the updated destination list
  return(dest)
}

as_integer = function(x) {
  suppressWarnings(as.integer(x))
}

make_valid_filename <- function(filename) {
  # First, convert accented characters to their ASCII equivalents,
  # then replace any character not matching [A-Za-z0-9_.-] with an underscore.
  stri_replace_all_regex(stri_trans_general(filename, "Latin-ASCII"), "[^\\w.-]+", "_")
}

atomic_class = function(val) {
  val = as.vector(val)
  cl = class(val)
  if (length(cl)>1) return(cl[length(cl)])
  cl
}

to_utf8 = function(str) {
  str = iconv(str, to="UTF-8", sub="")
  str = enc2utf8(str)
  str
}

select = dplyr::select

# Checks if x fits a Stat abbreviation
# E.g. is_stata_abbr("regr","reg","regress")
# would return TRUE
is_stata_abbr = function(x, short, long) {
  nlong = nchar(long)
  nshort = nchar(short)
  nx = nchar(x)

  ok = rep(FALSE, NROW(x))
  rows = which(nx >= nshort & nx <= nlong)
  if (length(rows)==0) return(ok)

  comp = stringi::stri_sub(long, 1, nx[rows])
  ok[x == comp] = TRUE
  ok
}

locals.vars.as.list = function(source = sys.frame(sys.parent(1))) {
  as.list(source)
}

copy.dir = function(from, to, ...) {
  if (!dir.exists(to)) dir.create(to, recursive = TRUE)
  res = file.copy(list.files(from, full.names = TRUE), to, recursive = TRUE, ...)
  invisible(all(res))
}

# removes all files in
remove.all.files.in.dir = function(clear.dir, recursive=FALSE) {
  if (!dir.exists(clear.dir)) return(TRUE)
  remove.files = list.files(clear.dir,all.files = FALSE,full.names = TRUE,recursive = recursive)
  file.remove(remove.files)
}

is_empty = function(x) {
  if (is.null(x) | all(is.na(x)) | length(x)==0) return(TRUE)
  if (isTRUE(x=="")) return(TRUE)
  return(FALSE)
}

is.empty = function(x) {
  if (is.null(x) | all(is.na(x)) | length(x)==0) return(TRUE)
  if (isTRUE(x=="")) return(TRUE)
  return(FALSE)
}

shorten.str = function(str,len=100, marker = "...") {
  is.bigger = nchar(str)>len
  str[is.bigger] = paste0(substring(str[is.bigger],1,len-nchar(marker)),marker)
  str
}


first.non.null = function(...) {
  args = list(...)
  for (val in args) {
    if (!is.null(val)) return(val)
  }
  return(NULL)

}

ws_to_single_space = function(str) {
  gsub("\t"," ", str) %>%  trimws_around(" ")
}

trimws_around = function(str, around, whitespace="[\t ]*") {
  pattern = paste0(whitespace,around,whitespace)
  str = gsub(pattern, around, str)
  str
}

set_missing_fields = function(x, ...) {
  new_vals = list(...)
  cols = names(new_vals)
  use = which(!cols %in% names(x))
  for (i in use) {
    x[[cols[i] ]] = new_vals[[i]]
  }
  x

}

set.fields = function(x, fields) {
  x[names(fields)] = fields
  x
}

select.cols = function(x, cols, create.missing=TRUE) {
  if (create.missing) {
    x = create.missing.cols(x,cols)
  }
  x[cols]
}



create.missing.cols = function(x, cols, val=NA) {
  cols = setdiff(cols,names(x))
  for (col in cols) {
    x[[col]] = val
  }
  x
}

has_col = function(x, col) {
  col %in% names(x)
}

has.col = function(x, col) {
  col %in% names(x)
}

rename.col = function(x, old, new) {
  restore.point("rename.col")
  pos = match(old,names(x))
  names(x)[pos] = new
  x
}

change_val = function(x, org, new) {
  if (length(org)==1) {
    rows = which(x==org)
  } else {
    rows = which(x %in% org)
  }
  x[rows] = new
  x
}

ensure_cols = function(x, cols, default=NA) {
  new = setdiff(cols, names(x))
  for (col in new) {
    x[[col]] = rep(default, NROW(x))
  }
  x
}

str.cutout = function(str, left, right) {
  paste0(substring(str,1, left-1),substring(str,right+1))
}

shorten.spaces = function(str) {
  return(ws_to_single_space(str))
}

rename.cols = function(x, old.cols, new.cols) {
  restore.point("rename.cols")
  inds = match(old.cols, names(x))
  old.cols = old.cols[!is.na(inds)]
  new.cols = new.cols[!is.na(inds)]
  inds = inds[!is.na(inds)]
  names(x)[inds] = new.cols
  x
}

na.if.null = function(x) {
  if (is.null(x)) return(NA)
  x
}


left_of = function(str, pattern, fixed=TRUE, not.found = str) {
  restore.point("left_of")
  if (length(not.found)==1) not.found = rep(not.found, length(str))
  if (fixed) {
    pos = stringi::stri_locate_first_fixed(str, pattern)
  } else {
    pos = stringi::stri_locate_first_regex(str, pattern)
  }
  res = substring(str, 1, pos[, 1] - 1)
  rows = is.na(pos[, 1])
  res[rows] = not.found[rows]
  res
}

omit.na.or.similar = function(dat, cols=names(dat)) {
  if (NROW(dat)==0) return(dat)
  rem = rep(FALSE, NROW(dat))
  for (col in cols) {
    if (is.numeric(dat[[col]])) {
      rem[!is.finite(dat[[col]])] = TRUE
    } else {
      rem[is.na(dat[[col]])] = TRUE
    }
  }
  dat[!rem, ]
}

standardizePath = function(file, mustWork=FALSE) {
  file = normalizePath(file, winslash = "/", mustWork=mustWork)
}


seq_rows = function(dat) {
  seq_len(NROW(dat))
}

random.string = function (n = 1, nchar = 12) {
  if (n == 1) {
    paste0(sample(c(LETTERS, letters), nchar, TRUE), collapse = "")
  }
  else {
    unlist(replicate(n, paste0(sample(c(LETTERS, letters),
                                      nchar, TRUE), collapse = "")))
  }
}


# Only adds col values if dat is not NULL
add_col = function(dat, ...) {
  if (is.null(dat)) return(dat)
  cols = list(...)
  if (NROW(dat)==0) {
    for (c in names(cols)) {
      dat[[c]] = rep(cols[[c]],0)
    }
  } else {
    for (c in names(cols)) {
      dat[[c]] = cols[[c]]
    }
  }
  dat
}


my_rank = function(x) {
  restore.point("my_rank")
  if (length(x)==0) return(integer(0))
  vals = unique(x)
  match(x, vals)
}

ensure_empty_types = function(x, cols, type="character") {
  if (NROW(x)>0) return(x)
  if (type=="character") {
    for (col in cols) {
      x[[col]] = character(0)
    }
  }
  x
}

rle_table = function(x) {
  rle = rle(x)
  start = c(1,cumsum(rle$lengths)+1)
  end = start[-1]-1
  start = start[-length(start)]
  tibble(start=start, end=end, length=rle$lengths, value = rle$values)
}

rle_block = function(x, ignore_val=NULL) {
  rle = rle(x)
  block_vals = seq_along(rle$values)
  if (length(ignore_val)>0) {
    zero_rows = rle$values %in% ignore_val
    block_vals[zero_rows] = 0
    uni = unique(block_vals[!zero_rows])
    block_vals[!zero_rows] = match(block_vals[!zero_rows],uni)
  }
  rep(block_vals, rle$lengths)
}

first.non.null = function(...) {
  args = list(...)
  for (val in args) {
    if (!is.null(val)) return(val)
  }
  return(NULL)

}

list_find_null_entries = function(li) {
  which(!is.na(match(li,list(NULL))))
}

list_remove_null_entries = function(li) {
  null.rows = which(!is.na(match(li,list(NULL))))
  if (length(null.rows)>0) {
    return(li[-null.rows])
  }
  li
}
bind_rows_with_parent_fields = function(parent.df,df.field,  fields, parent.fields, parent.row.field = "..PARENT.ROW") {
  restore.point("bind_rows_with_parent_fields")
  li = parent.df[[df.field]]
  names(li) = NULL

  null_rows = list_find_null_entries(li)

  if (length(null_rows)>0) {
    li = li[-null_rows]
    parent.df = parent.df[-null_rows,]
  }

  df = bind_rows(li, .id=parent.row.field)
  df[[parent.row.field]] = as.integer(df[[parent.row.field]])
  for (field in fields) {
    df[[field]] = parent.df[[field]][df[[parent.row.field]]]
  }

  use.cols = setdiff(colnames(df), parent.row.field)
  df = df[,use.cols]
}



readRDS.or.null = function(file) {
  if (!file.exists(file)) return(NULL)
  readRDS(file)
}

na.remove = function(x) {
  x[!is.na(x)]
}

na.false = function(x) {
  na.val(x, FALSE)
}

na.val = function(x, val=0) {
  x[is.na(x)] = val
  x
}

is.true = function(x) {
  val = x == TRUE
  val[is.na(x)] = FALSE
  val
}

most.common = function(x) {
  uniqx <- unique(na.omit(x))
  uniqx[which.max(tabulate(match(x, uniqx)))]
}

remove_cols = function(x, cols) {
  x[,setdiff(colnames(x),cols)]
}

remove.cols = function(x, cols) {
  x = x[,setdiff(colnames(x),cols)]
}


# Perform a left join but first drop columns in y or x
# that also exist in x (y) and are not part of by
left_join_overwrite = function(x,y,by,..., yfields=NULL, drop_in="y") {
  if (!is.null(yfields)) {
    y = y[,intersect(names(y),union(yfields, by)), drop=FALSE]
  }
  drop.cols = setdiff(intersect(colnames(x), colnames(y)),by)

  if (length(drop.cols)>0) {
    if (drop_in=="y") {
      y = y[, setdiff(colnames(y), drop.cols)]
    } else {
      x = x[, setdiff(colnames(x), drop.cols)]
    }
  }
  left_join(x,y,by=by,...)
}


parse_eval = function(cmd, envir=parent.frame()) {
  if (is.null(cmd)) return(invisible(NULL))
  eval(parse(text=cmd),envir = envir)
}



left_join_overlap = function(x, y, by_x, by_y, mult="all", type="any", nomatch=NA) {
  dt_x = as.data.table(x)
  dt_y = as.data.table(y,key = by_y)
  dt_ol = foverlaps(dt_x, dt_y, mult=mult, type=type, which=FALSE, by.x=by_x)
  as_tibble(dt_ol)
}

match_overlap = function(xstart,xend,ystart,yend, mult="all", type="any") {
  restore.point("match_all_rounded")
  dt_x = data.table(ind_x = seq_along(xstart), xstart=xstart, xend=xend,key = c("xlow","xhigh"))
  dt_y = data.table(ind_y = seq_along(ystart), ystart=ystart, yend=yend,key = c("ylow","yhigh"))

  ol = foverlaps(dt_x, dt_y, mult=mult, type=type, which=TRUE, nomatch=NULL)
  res = tibble(ind_x=dt_x$ind_x[ol[[1]]],ind_y = dt_y$ind_y[ol[[2]]])
  res
}
# Remove from x all locations that overlap with a location in y
remove.overlapping.loc = function(x, y, by=c("line", "start","end"), mode=c("remove","keep","mark")[1]) {
  restore.point("remove.overlapping.loc")
  library(data.table)
  loc1 = as.data.table(x)
  setkeyv(loc1, by)

  loc2 = as.data.table(y)
  setkeyv(loc2, by)

  ol = foverlaps(loc1, loc2, by.x=by, by.y=by, which=TRUE, nomatch=NA)
  not.ol = sort(unique(ol$xid[is.na(ol$yid)]))
  if (mode=="mark") {
    x$overlapping = TRUE
    x$overlapping[!not.ol] = FALSE
    return(x)
  }
  if (mode =="remove") {
    x[not.ol,,drop=FALSE]
  } else if (mode == "keep") {
    if (length(not.ol)==0) return(x)
    x[-not.ol,,drop=FALSE]
  }
}

keep.overlapping.loc = function(...) {
  remove.overlapping.loc(..., mode="keep")
}

locate_all_as_df = function(txt, regexpr.li) {
  restore.point("locate_all_as_df")
  locs.li = lapply(regexpr.li, function(regexpr) {
    str_locate_all(txt, regexpr)
  })

  loc.df = bind_rows(lapply(seq_along(locs.li), function(i) {
    type = names(locs.li)[i]
    locs = bind_rows(lapply(seq_along(locs.li[[i]]), function(row) {
      loc = locs.li[[i]][[row]]
      if (NROW(loc)==0) return(NULL)
      loc = as_tibble(loc)
      loc$line = row
      loc$type = type
      loc$pos = 1:NROW(loc)
      loc
    }))
    locs
  }))
  if (NROW(loc.df)==0) {
    loc.df = tibble(start=integer(0),end=integer(0), line=integer(0), type=character(0), pos=integer(0))
  }

  loc.df$str = substring(txt[loc.df$line], loc.df$start, loc.df$end)
  loc.df$nchar = loc.df$end-loc.df$start
  loc.df
}


ends.with.text = function(txt, end.size=4) {
  str = trimws(txt)
  rhs = substring(str, nchar(str)-end.size,nchar(str))
  grepl("[a-zA-z]",rhs,fixed=FALSE)

}

seq_rows = function(x) {
  seq_len(NROW(x))
}

from_to = function(from, to, min=from, max=to) {
  from = max(from, min)
  to = min(to, max)
  if (from > to) return(NULL)
  from:to
}


remove.start.strings = function(str, starts) {
  restore.point("remove.start.strings")
  for (s in starts) {
    rows = which(startsWith(str, s))
    if (length(rows)>0) {
      str[rows] = trimws(str.right.of(str[rows],s))
    }
  }
  str
}


read_lines_from_tail = function(file, n=10) {
  restore.point("read_lines_from_tail")
  # Only faster under unix, which has a tail command
  file = normalizePath(file)
  if (.Platform$OS.type == "unix") {
    cmd = paste0("tail -n ", n, ' "', file,'"')
    res = system(cmd, intern=TRUE)
  } else {
    txt = readLines(file)
    res = tail(txt,n)
  }
  res
}

parse.as.call = function (text, allow.null = TRUE)
{
  if (is.null(text)) {
    if (allow.null)
      return(NULL)
    stop("parse.as.call was called with text=NULL")
  }
  parse(text = text)[[1]]
}

find.call.variables = function(call){
  if (is.name(call))
    return(as.character(call))
  if (length(call) <= 1)
    return(NULL)
  names = lapply(call[-1], function(e1) {
    find.call.variables(e1)
  })
  names = unique(unlist(names, use.names = FALSE))
  names
}

rstudio_job = function(name, expr, libs=NULL, wdir = getwd(), script.dir = tempdir(), importEnv=TRUE) {
  expr = substitute(expr)
  restore.point("as_job")
  code = deparse1(expr)

  #code = paste0('setwd("',wdir,'")\n', code)
  if (!is.null(libs)) {
    code = paste0(paste0("library(", libs,")", collapse="\n"), "\n", code)
  }
  cat("\nRun \n\n",code,"\n\n")

  script.file = file.path(script.dir, paste0(name,".R"))
  writeLines(code, script.file)
  rstudioapi::jobRunScript(path = script.file,workingDir = wdir, name = name,importEnv = importEnv)

}

writeUtf8 = function(x, file, bom=F) {
  if (length(x)>1) {
    x = paste0(x, collapse="\n")
  }
  con <- file(file, "wb")
  if(bom) writeBin(BOM, con, endian="little")
  writeBin(charToRaw(x), con, endian="little")
  close(con)
}


create_dirs_of_files = function (files, must.have = NULL) {
  restore.point("create_dirs_of_files")
  dirs = unique(dirname(files))
  if (!is.null(must.have)) {
    if (!all(stringi::stri_detect_fixed(files, must.have))) {
        stop(paste0("Not all directories contain the pattern ",
            must.have))
    }

  }
  for (dir in dirs) {
      if (!dir.exists(dir)) {
          dir.create(dir, recursive = TRUE)
      }
  }
}

file.exists.in.any.dir = function(files, dirs) {
  exists = rep(FALSE,length(files))
  for (dir in dirs) {
    exists = exits | file.exists(file.path(dir,files))
  }
  exists
}

# Get a function but set its enclosing environment
# by default to the environment of the caller
fun_with_env = function(fun, env=parent.frame()) {
  environment(fun) = env
  fun
}


with_random_seed = function(expr, seed = 1234567890) {
  old.seed = get(".Random.seed", .GlobalEnv)
  set.seed(seed)
  ret = eval(expr)
  restore.point("with_random_seed")
  assign(".Random.seed", old.seed, .GlobalEnv)
  runif(1)
  return(ret)
}

is_valid_zip_file <- function(path) {

  ## ---- preliminaries ---------------------------------------------------
  if (!file.exists(path)) return(FALSE)

  con <- file(path, open = "rb")
  on.exit(close(con), add = TRUE)

  ## ---- 1) signature check ---------------------------------------------
  sig <- readBin(con, what = "raw", n = 2L)
  # legal signatures for local-file header, EOCD for empty archive, or spanned archives
  if (!identical(sig[1],0x50)) return(FALSE)
  if (!identical(sig[2],0x4b)) return(FALSE)
  return(TRUE)

  valid_sig <- list(
    c(0x50, 0x4b, 0x03, 0x04),  # PK\x03\x04  -> normal archive
    c(0x50, 0x4b, 0x05, 0x06),  # PK\x05\x06  -> empty archive
    c(0x50, 0x4b, 0x07, 0x08)   # PK\x07\x08  -> spanned
  )
  if (!any(vapply(valid_sig, identical, logical(1), sig)))
    return(FALSE)
}

is_valid_pdf_file <- function(path, quick=FALSE) {
  con  <- file(path, "rb")
  on.exit(close(con), add = TRUE)

  # Read first 8 bytes for the header
  header <- rawToChar(readBin(con, "raw", n = 8))
  starts_ok <- grepl("^%PDF-[12]\\.[0-9]", header)
  if (!starts_ok) return(FALSE)
  if (quick) return(starts_ok)

  # Read last ~10 bytes for the EOF marker
  seek(con, where = -10, origin = "end")
  tail   <- rawToChar(readBin(con, "raw", n = 10))

  ends_ok   <- grepl("%%EOF", tail)

  starts_ok && ends_ok
}

zip_dir = function(dir, dest_file, overwrite=TRUE) {
  if (!dir.exists(dir)) {
    cat("\nDirectory does not exist: ", dir,"\n")
    return(FALSE)
  }
  if (!overwrite & file.exists(dest_file)) {
    cat("\nZIP file", dest_file, "already exists.\n")
    return(FALSE)
  }

  dir = normalizePath(dir, mustWork = TRUE)
  dest_file = normalizePath(dest_file, mustWork = FALSE)

  files = list.files(dir, recursive = TRUE, all.files = TRUE, no.. = TRUE)

  old_wd = getwd()
  on.exit(setwd(old_wd), add = TRUE)

  setwd(dirname(dir))
  utils::zip(zipfile = dest_file, files = file.path(basename(dir), files))
  return(TRUE)
}

```
# END OF FILE: /home/rstudio/repbox/repboxUtils/R/tools.R

-----------------------------------------------------------


# FILE: /home/rstudio/repbox/repboxUtils/R/trash_bin.R
```
# Call trash-restore in linux shell to restore trash

example = function() {
  trash_file = c("~/repbox/test_tab.html","~/repbox/test_table.html")
  trash_file = "~/repbox/temp/to_trash"

}

dir_to_trash = function(trashed_dir) {
  trash_put(trashed_dir)
}

trash_put = function(trashed_file) {
  trash_file = normalizePath(trashed_file)
  cmd = paste0('trash-put ', paste0('"', trashed_file,'"', collapse=" "))
  cat(cmd)
  system(cmd)
}

trash_list = function(dir = "~") {
  cmd = paste0('trash-list')
  system(cmd)
}

```
# END OF FILE: /home/rstudio/repbox/repboxUtils/R/trash_bin.R

-----------------------------------------------------------



# Package regtranslate

{regtranslate}



## Format of proposed changes to code  files

When you suggest changes to code or text files or completely new files, you MUST use the following format for each modification. Each change must be enclosed in a `!MODIFICATION` block.

### Overall Structure

Each modification block has three parts:
1.  Start and end markers: `!MODIFICATION {{what}}` and `!END_MODIFICATION {{what}}`, where {{what}} is just a short reference to what is modified, file name or function name with with file. It will not be parsed but makes it easier for a human to understand blocks.
2.  A metadata block in **TOML format**. This block ends with a `---` separator line.
3.  A code payload block, which is a standard markdown code fence.

```
!MODIFICATION {{what}}
# TOML metadata goes here
# ...
---
```language
# New code payload goes here
```
!END_MODIFICATION {{what}}
```

We have two possible scopes for modification:
  - file (replaces complete file) or
  - function (replaces an R function).

### **Scope 1: `file`**

Use this format to create a new file or to completely rewrite an existing one.

**Required Fields:**
*   `scope = "file"`
*   `file` (string): The path to the file. Very important: state the path of the file as shown in the files header above. If there is a complete absolute path, also show the complete absolute path here.
*   `description` (string): A brief explanation of the change in quotes ""

#### **Example 1.1: Creating or modifying a file**
!MODIFICATION new_helpers.R
scope = "file"
file = "/home/rstudio/myproject/R/new_helpers.R"
description = "Create a new file for helper functions."
---
```r
# A new helper function
say_hello = function(name) {
  paste0("Hello, ", name)
}
```
!END_MODIFICATION new_helpers.R


### **Scope 2: `function`**

Use this fomrat to replace an existing function or to insert a new function. The new code payload should contain the complete function, including any preceding comments.

#### **Fields for replacing an existing function:**
*   `scope = "function"`
*   `file` (string): The path to the file. Very important: state the path of the file as shown in the files header above. If there is a complete absolute path, also show the complete absolute path here.
*   `function_name` (string): The name of the function to be replaced.
*   `description` (string): A brief explanation of the change in quotes.

#### **Fields for inserting a new function:**
*   `scope = "function"`
*   `file` (string): The path to the file. Very important: state the path of the file as shown in the files header above. If there is a complete absolute path, also show the complete absolute path here.
*   `description` (string): A brief explanation of the change, enclose in quotes.
*   **One of** the following fields to specify the insertion point. They are mutually exclusive.
    *   `insert_top = true`: Insert at the top of the file.
    *   `insert_bottom = true`: Insert at the bottom of the file.
    *   `insert_before_fun = "function_name"`: Insert before the specified function.
    *   `insert_after_fun = "function_name"`: Insert after the specified function.


#### **Example 2.1: Replacing an existing function**
!MODIFICATION calculate_sum utils.R
scope = "function"
file = "R/utils.R"
function_name = "calculate_sum"
description = "Update `calculate_sum` to handle NA values correctly.""
---
```r
#' Calculate the sum of a vector, ignoring NAs
calculate_sum = function(vec) {
  sum(vec, na.rm = TRUE)
}
```
!END_MODIFICATION calculate_sum utils.R

#### **Example 2.2: Inserting a new function at the bottom of a file (here was an absolute file path given)**
!MODIFICATION is_positive in R/utils.R
scope = "function"
file = "/home/myuser/mypkg/R/utils.R"
insert_bottom = true
description = "Add a new helper function to check for positivity."
---
```r

#' Check if a number is positive
is_positive = function(n) {
  n > 0
}
```
!END_MODIFICATION is_positive in R/utils.R

#### **Example 2.3: Inserting a new function after a specific function**
!MODIFICATION is_negative in R/utils.R
scope = "function"
file = "R/utils.R"
insert_after_fun = "is_positive"
description = "Add a new helper function `is_negative` after `is_positive`."
---
```r

#' Check if a number is negative
is_negative = function(n) {
  n < 0
}
```

##################################
# Your Task
##################################

My whole repbox pipeline works well for this Stata code:

```
ivreg2 y (x1=i1) if i1>1
```

But fails for 

```
ivreg2 y (x1=i1)if i1>1
```

My guess is that there is a bug when extracting the if condition somewhere (assuming a space before it). Can you detect the bug in the provided code and fix it? If you don't see the bug it might be elsewhere in my pipeline. Explain also in words before you provide a potential code fix.





