# Generated by repboxGithub::gha_rp_write_run_config
gha_rp_run_config = 
list(artid = "gha_test", sup_url = "https://klein.mathematik.uni-ulm.de/repbox_temp/rp_gha.zip", 
    work_dir = "gha_work", output_dir = "gha_output/bundle", 
    artifact_name = "gha-rp-results", overwrite = TRUE, timeout = 600, 
    create_mod_dir = TRUE, capture_reg_info = TRUE, capture_scalar_info = TRUE, 
    stop.on.error = TRUE)
