gha_rp_url_join = function(base_url, file_name) {
  base_url = stringi::stri_replace_last_regex(base_url, "/+$", "")
  file_name = stringi::stri_replace_first_regex(file_name, "^/+", "")
  stringi::stri_paste(base_url, file_name, sep = "/")
}

#' Copy the original supplement ZIP to the server location used by gha_rp
#'
#' If no original ZIP is available, the function can create one from the
#' current /org folder via repboxRun::rb_make_org_zip.
#'
#' @export
gha_rp_stage_sup_zip = function(
  project_dir,
  server_dir,
  sup_zip = NULL,
  server_file_name = NULL,
  url_base = NULL,
  overwrite = TRUE,
  create_zip_from_org = TRUE,
  local_zip_file = file.path(project_dir, "rp_zip", paste0(basename(project_dir), "_org.zip")),
  overwrite_local_zip = FALSE
) {
  restore.point("gha_rp_stage_sup_zip")

  project_dir = normalizePath(project_dir, mustWork = FALSE)

  sup_zip = repboxRun:::rb_ensure_sup_zip(
    project_dir = project_dir,
    sup_zip = sup_zip,
    zip_file = local_zip_file,
    overwrite = overwrite_local_zip,
    create_from_org = create_zip_from_org
  )

  if (is.null(sup_zip) || !file.exists(sup_zip)) {
    stop("Could not determine a valid supplement ZIP file.")
  }
  sup_zip = normalizePath(sup_zip, mustWork = TRUE)

  artid = basename(project_dir)
  safe_base = basename(sup_zip)
  safe_base = stringi::stri_replace_all_regex(safe_base, "[^A-Za-z0-9._-]+", "_")

  if (is.null(server_file_name)) {
    server_file_name = "rp_gha.zip"
  }

  dir.create(server_dir, recursive = TRUE, showWarnings = FALSE)
  server_file = file.path(server_dir, server_file_name)

  ok = file.copy(
    from = sup_zip,
    to = server_file,
    overwrite = overwrite,
    copy.mode = TRUE,
    copy.date = TRUE
  )
  cat(paste0("\nCopied reproduction package of ", artid, " to ", server_file,"\n"))
  if (!isTRUE(ok)) {
    stop("Could not copy the supplement ZIP to the server directory.")
  }

  res = list(
    artid = artid,
    sup_zip = sup_zip,
    server_dir = normalizePath(server_dir, mustWork = FALSE),
    server_file = normalizePath(server_file, mustWork = FALSE),
    server_file_name = server_file_name,
    size_mb = file.size(server_file) / 1e6,
    md5 = unname(tools::md5sum(server_file))
  )

  if (!is.null(url_base)) {
    res$url = gha_rp_url_join(url_base, server_file_name)
  }

  res
}

#' Write the run_config.R file used by the gha_rp Github Actions repo
#'
#' @export
gha_rp_write_run_config = function(
  repo_dir = "/home/rstudio/repbox/gha/gha_rp",
  artid,
  sup_url,
  overwrite = TRUE,
  timeout = 60 * 5,
  create_mod_dir = TRUE,
  capture_reg_info = TRUE,
  capture_scalar_info = TRUE,
  stop.on.error = TRUE,
  work_dir = "gha_work",
  output_dir = "gha_output/bundle",
  artifact_name = "gha-rp-results"
) {
  restore.point("gha_rp_write_run_config")

  dir.create(repo_dir, recursive = TRUE, showWarnings = FALSE)

  cfg = list(
    artid = artid,
    sup_url = sup_url,
    work_dir = work_dir,
    output_dir = output_dir,
    artifact_name = artifact_name,
    overwrite = overwrite,
    timeout = timeout,
    create_mod_dir = create_mod_dir,
    capture_reg_info = capture_reg_info,
    capture_scalar_info = capture_scalar_info,
    stop.on.error = stop.on.error
  )

  file = file.path(repo_dir, "run_config.R")
  txt = c(
    "# Generated by repboxGithub::gha_rp_write_run_config",
    "gha_rp_run_config = ",
    paste(capture.output(dput(cfg)), collapse = "\n")
  )
  writeLines(txt, file)

  invisible(cfg)
}

#' Stage the supplement ZIP and refresh the gha_rp run_config.R
#'
#' @export
gha_rp_prepare_repo = function(
  project_dir,
  server_dir,
  url_base,
  repo_dir = "/home/rstudio/repbox/gha/gha_rp",
  sup_zip = NULL,
  server_file_name = NULL,
  overwrite = TRUE,
  timeout = 60 * 5,
  create_mod_dir = TRUE,
  capture_reg_info = TRUE,
  capture_scalar_info = TRUE,
  stop.on.error = TRUE,
  work_dir = "gha_work",
  output_dir = "gha_output/bundle",
  artifact_name = "gha-rp-results"
) {
  restore.point("gha_rp_prepare_repo")

  staged = gha_rp_stage_sup_zip(
    project_dir = project_dir,
    server_dir = server_dir,
    sup_zip = sup_zip,
    server_file_name = server_file_name,
    url_base = url_base,
    overwrite = overwrite
  )

  cfg = gha_rp_write_run_config(
    repo_dir = repo_dir,
    artid = basename(project_dir),
    sup_url = staged$url,
    overwrite = overwrite,
    timeout = timeout,
    create_mod_dir = create_mod_dir,
    capture_reg_info = capture_reg_info,
    capture_scalar_info = capture_scalar_info,
    stop.on.error = stop.on.error,
    work_dir = work_dir,
    output_dir = output_dir,
    artifact_name = artifact_name
  )

  invisible(list(
    staged_sup = staged,
    run_config = cfg
  ))
}

gha_rp_find_bundle_dir = function(root_dir) {
  restore.point("gha_rp_find_bundle_dir")

  files = list.files(
    root_dir,
    pattern = "repbox_results\\.Rds$",
    recursive = TRUE,
    full.names = TRUE
  )

  if (length(files) == 0) {
    return(NULL)
  }

  stata_pat = paste0(
    .Platform$file.sep, "repbox",
    .Platform$file.sep, "stata",
    .Platform$file.sep
  )
  keep = stringi::stri_detect_fixed(files, stata_pat)
  files = files[keep]

  if (length(files) == 0) {
    return(NULL)
  }

  normalizePath(dirname(dirname(dirname(files[1]))), mustWork = TRUE)
}

#' Download the latest raw Stata artifact from gha_rp and import it locally
#'
#' @export
gha_rp_download_stata_raw_results = function(
  repo,
  project_dir,
  overwrite = TRUE,
  verify = TRUE,
  local_input_zip = NULL,
  password = NULL
) {
  restore.point("gha_rp_download_stata_raw_results")

  project_dir = normalizePath(project_dir, mustWork = FALSE)

  if (is.null(local_input_zip)) {
    guessed_zip = try(repboxRun:::rb_get_sup_zip(project_dir), silent = TRUE)
    if (!inherits(guessed_zip, "try-error") && length(guessed_zip) > 0 &&
        !is.na(guessed_zip[1]) && file.exists(guessed_zip[1])) {
      local_input_zip = guessed_zip[1]
    }
  }

  temp_dir = file.path(project_dir, "temp", "gha_rp")
  if (dir.exists(temp_dir)) {
    unlink(temp_dir, recursive = TRUE, force = TRUE)
  }
  dir.create(temp_dir, recursive = TRUE, showWarnings = FALSE)

  artifact_zip = file.path(temp_dir, "gha_rp_results.zip")
  gh_download_artifact(repo, destfile = artifact_zip)
  utils::unzip(artifact_zip, exdir = temp_dir)

  z7_files = list.files(
    temp_dir,
    pattern = "\\.7z$",
    recursive = TRUE,
    full.names = TRUE,
    ignore.case = TRUE
  )

  search_dir = temp_dir
  if (length(z7_files) > 0) {
    search_dir = file.path(temp_dir, "unz7")
    dir.create(search_dir, recursive = TRUE, showWarnings = FALSE)
    extract.7z(path = search_dir, zip = z7_files[1], password = password)
  }

  bundle_dir = gha_rp_find_bundle_dir(search_dir)
  if (is.null(bundle_dir)) {
    stop("Could not find a raw Stata bundle in the downloaded artifact.")
  }

  res = repboxRun:::rb_import_gha_stata_bundle(
    project_dir = project_dir,
    bundle_dir = bundle_dir,
    overwrite = overwrite,
    verify = verify,
    local_input_zip = local_input_zip
  )

  invisible(res)
}
