example = function() {

  library(repboxRun)
  library(repboxEJD)
  #artid = "ecta_84_2_6"
  artid = ""
  #rstudioapi::filesPaneNavigate(paste0("~/repbox/projects_gha/",artid))

  artid = "aejmic_17_2_2"
  projects.dir = "~/repbox/projects_test"

  #artid = "testsupp"
  repbox_init_ejd_project(artid=artid, projects.dir=projects.dir)

  Project_dir = file.path(projects.dir,artid)
  steps = repbox_steps_from(file_info = TRUE)
  #steps = repbox_steps_from(reproduction = TRUE, map=TRUE, html = TRUE)
  #steps = repbox_steps_from(mr_base = TRUE)
  #steps = repbox_steps_from(html=TRUE)
  html_opts = repbox_html_opts(make_what = c("ejd","general"))
  #stata_opts = repbox_stata_opts(timeout = 5*60, rerun.failed.included.do = FALSE)
  #opts = repbox_run_opts(stop.on.error = FALSE,html_opts=html_opts)
  #steps = repbox_steps_from(map = TRUE,html=FALSE)
  #steps = repbox_steps_from(file_info = TRUE,art = TRUE,reproduction = FALSE)
  options(warn=1)
  opts = repbox_run_opts(stop.on.error = !TRUE,timeout = 10*60, art_opts = repbox_art_opts(overwrite=TRUE), html_opts = html_opts)
  repbox_run_project(Project_dir,lang="stata", steps=steps, opts=opts)
  rstudioapi::filesPaneNavigate(Project_dir)
  rstudioapi::filesPaneNavigate(paste0("~/repbox/projects_gha/",artid))

  #repboxExplore::make_reg_playground(project_dir, steps = 16)

  steps = repbox_steps_from(html = TRUE)
  html_opts = repboxHtml::repbox_html_opts_just_ejd()
  repbox_run_project(project_dir,lang="stata", steps=steps, opts=repbox_run_opts(html_opts = html_opts))


  library(repboxRun)
  project_dir = "/home/rstudio/repbox/projects_test/testsupp"
  options(warn=1)
  restore.point.options(display.restore.point = !TRUE)
  html_opts = repboxHtml::repbox_html_opts_just_ejd()
  opts = repbox_run_opts(stop.on.error = FALSE, timeout = 10, html_opts = html_opts)
  steps = repbox_steps_from(file_info = TRUE,static_code=TRUE, art=FALSE, reproduction = TRUE,reg = TRUE,mr_base = TRUE,map = FALSE,html = TRUE)
  repbox_run_project(project_dir, steps=steps, opts=opts)

  rstudioapi::filesPaneNavigate(project_dir)

  #dap = readRDS(file.path(project_dir, "metareg/dap/stata/dap.Rds"))
  #plot.dap(dap)

  library(repboxRun)
  project_dir = "/home/rstudio/repbox/projects_reg/aejmac_6_3_1"
  project_dir = "/home/rstudio/repbox/projects_reg/testsupp"
  project_dir = "/home/rstudio/repbox/projects_reg/aejpol_3_4_8"
  project_dir = "/home/rstudio/repbox/projects_reg/aejpol_7_2_11"

  #steps = repbox_run_steps_from(art = TRUE)
  #restorepoint::restore.point.options(display.restore.point = !TRUE)
  steps = repbox_run_steps_from(reproduction =  TRUE,map=TRUE)
  opts = repbox_run_opts(art_opts = repbox_art_opts(overwrite=TRUE), html_opts = repbox_html_opts(add_art_source_tab = TRUE))
  repbox_run_project(project_dir, steps=steps, opts=opts)

  rstudioapi::filesPaneNavigate(project_dir)

}

#' @title Run repbox analysis for a project (article with supplement)
#'
#' @param project_dir Path to project directory
#' @param lang Language(s) to run analysis for can be any subset of c("r","stata")
#' @param steps Vector of analysis steps to run. Use repbox_steps_from function to create this.
#' @param opts Options for analysis steps generated by repbox_run_opts function.
#' @export
repbox_run_project = function(project_dir, lang = c("stata","r"), steps = repbox_steps_all(), opts = repbox_run_opts()) {
  restore.point("repbox_run_project")
  options(dplyr.summarise.inform = FALSE)

  if (!dir.exists(project_dir)) {
    cat("\nProject directory", project_dir, "does not exist!\n")
    return(invisible(FALSE))
  }
  repbox_set_problem_options(project_dir=project_dir, fail_action=opts$problem_fail_action)
  repbox_set_current_project_dir(project_dir)
  dap.file = paste0(project_dir,"/metareg/dap/stata/dap.Rds")

  show_title = function(str) {
    cat("\n++++++++++++++++++++++++++++++++++++++++++++++++++++\n",str,"\n+++++++++++++++++++++++++++++++++++++++++++++++++++++\n")
  }

  org.dir = file.path(project_dir,"org")
  sup.dir = file.path(project_dir,"mod")
  repbox.dir = file.path(project_dir, "repbox")
  repbox.stata.dir = file.path(project_dir, "repbox/stata")
  repbox.r.dir = file.path(project_dir, "repbox/r")

  # Delete existing problems directory
  problems.dir = file.path(project_dir, "problems")
  if (opts$remove_existing_problems) {
    remove.dir(problems.dir, must.contain = project_dir)
  }


  artid = basename(project_dir)

  parcels = list(.files = list())


  if (steps$file_info) {
    show_title("Extract supplement's basic file information")
    repbox_log_step_start(project_dir, "file_info", opts=NULL)
    parcels = sup_save_basic_info(project_dir, parcels)

    # Also save article basic info
    repboxArt::art_save_basic_info(project_dir)

    repbox_log_step_end(project_dir, "file_info")
  }

  parcels = repdb_load_parcels(project_dir,"sup", parcels)
  sup_info = parcels$sup
  if (!is.null(sup_info)) {
    if (isTRUE(!sup_info$has_r) & "r" %in% lang) {
      cat("\nNo R scripts found...\n")
      lang = setdiff(lang, "r")
    }
    if (isTRUE(!sup_info$has_stata) & "stata" %in% lang) {
      cat("\nNo Stata do scripts found...\n")
      lang = setdiff(lang, "stata")
    }
  }

  if (steps$static_code) {
    show_title("Static analysis of code and its comments")
    repbox_log_step_start(project_dir, "static_code", opts)

    if (!dir.exists(repbox.dir)) dir.create(repbox.dir)

    # Create file info from /org folder
    parcels$.files$org = make.project.files.info(project_dir,for.org=TRUE, for.mod = FALSE)$org
    # Save script content in Rds files in parcels
    if (opts$make_script_parcel) {
      parcels = repbox_make_script_parcel(project_dir, parcels)
    }
    if ("stata" %in% lang) {
      cat("\n  Stata static code analysis...\n\n")
      parcels = repbox_stata_static_parcel(project_dir, parcels=parcels, opts=opts)
      parcels = repboxCodeText::code_project_find_refs(project_dir, parcels=parcels)
    }
    if ("r" %in% lang) {
      cat("\n  R static code analysis...\n\n")
      parcels = repboxR::repbox_project_static_analyse_r(project_dir,parcels=parcels, opts=opts$r_opts)
    }

    repbox_log_step_end(project_dir, "static_code")
  }


  if (steps$art) {
    show_title("Extract information from article text")
    repbox_log_step_start(project_dir, "art", opts)
    art_update_project(project_dir, opts=opts$art_opts)
    repbox_log_step_end(project_dir, "art")
  }

  # If we run the reproduction step again, we will clear most results
  if (steps$reproduction) {
    show_title("Reproduction of initial supplement")
    repbox_log_step_start(project_dir, "reproduction", opts)

    if (dir.exists(sup.dir)) remove.dir(sup.dir,must.contain = project_dir)

    # Keep file dates so that we can better
    # see which files are overwritten when comparing
    # original to modified supplement
    copy.dir(org.dir, sup.dir,copy.date=TRUE)
    unzip.zips(sup.dir)
    make.project.files.info(project_dir, for.mod = TRUE, for.org=TRUE)

    # Remove all files except for code files in org folder
    if (opts$slimify_org) {
      slimify.org.dir(project_dir)
    }


    if ("stata" %in% lang) {
      remove.dir(repbox.stata.dir,must.contain = project_dir)
      dir.create(repbox.stata.dir)

      dap_and_cache_remove_from_project(project_dir)
      res = repbox_project_run_stata(project_dir,opts=opts$stata_opts)
      parcels = repbox_save_stata_run_parcels(project_dir, parcels)
      parcels = make_parcel_stata_do_run_info(project_dir, parcels)
    }
    if ("r" %in% lang) {
      parcels = repbox_project_run_r(project_dir, opts=opts$r_opts,parcels = parcels)
      parcels = repbox_project_extract_r_results(project_dir, parcels, opts=opts$r_opts)
    }
    make.project.files.info(project_dir, for.mod = TRUE, for.org=FALSE)
    repbox_log_step_end(project_dir, "reproduction")
  }

  parcels = repdb_load_parcels(project_dir, "stata_run_info", parcels=parcels)
  has_stata_regs = isTRUE(parcels$stata_run_info$stata_run_info$reg_runs > 0)
  has_ok_stata_regs = isTRUE(parcels$stata_run_info$stata_run_info$ok_reg_runs > 0)


  if (steps$reg & "stata" %in% lang & has_ok_stata_regs) {
    show_title("Rerun Stata scripts to extract regression information")
    repbox_log_step_start(project_dir, "reg", opts)

    dap = get.project.dap(project_dir, make.if.missing = TRUE)

    if (opts$store_data_caches) {
      cache.dir = file.path(project_dir, "metareg/dap/stata/cache")
      if (!dir.exists(cache.dir)) dir.create(cache.dir,recursive = TRUE)
      store.data = dap.to.store.data(dap, cache.dir)
    } else {
      store.data = NULL
    }

    if (dir.exists(sup.dir)) remove.dir(sup.dir,must.contain = project_dir)
    copy.dir(org.dir, sup.dir,copy.date=TRUE)
    unzip.zips(sup.dir)

    stata_opts = opts$stata_opts
    stata_opts$extract.reg.info = TRUE
    stata_opts$extract.scalar.vals = TRUE
    stata_opts$store.data = store.data
    parcels = repbox_project_run_stata(project_dir,opts=stata_opts, parcels=parcels)
    parcels = repbox_save_stata_reg_run_parcels(project_dir, parcels)
    #restore.point("hfjhfksf")
    res = dap_create_stata_scalar_info(project_dir = project_dir, dap=dap, scalar_df = parcels$stata_scalar$stata_scalar)
    repbox_log_step_end(project_dir, "reg")
  } else if (steps$reg & "stata" %in% lang & !has_stata_regs) {
    show_title("Rerun Stata scripts to extract regression information")
    cat("\n  No Stata regression command was originally run.\n")
  } else if (steps$reg & "stata" %in% lang & !has_ok_stata_regs) {
    show_title("Rerun Stata scripts to extract regression information")
    cat("\n  No Stata regression command was originally run without error.\n")
  }


  if (steps$mr_base & "stata" %in% lang & has_ok_stata_regs) {
    show_title("Base Metareg")
    repbox_log_step_start(project_dir, "mr_base", opts)
    res = mr_base_run_study(project_dir, stop.on.error = opts$stop.on.error,create.repdb = TRUE,stata_version = opts$stata_version)
    repbox_log_step_end(project_dir, "mr_base")
  }

  parcels = NULL
  if (steps$repbox_repdb) {
    show_title("Store repbox repdb")
    repbox_log_step_start(project_dir, "repbox_repdb", opts)
    parcels = repbox_to_repdb(project_dir, parcels)
    repbox_log_step_end(project_dir, "repbox_repdb")
  }

  if (steps$map) {
    show_title("Create Mappings")
    repbox_log_step_start(project_dir, "map", opts)
    parcels = repboxMap::map_repbox_project(project_dir,parcels = parcels, opts = opts$map_opts)
    repbox_log_step_end(project_dir, "map")
  }

  if (steps$html) {
    show_title("Create HTML Reports")
    repbox_log_step_start(project_dir, "html", opts)
    repboxHtml::repbox_project_html(project_dir,lang=lang,parcels = parcels, opts = opts$html_opts)
    repbox_log_step_end(project_dir, "html")
  }
  return(TRUE)
}

rb_log_step_start = function(rb, step) {
  repbox_log_step_start(rb$project_dir, step, opts=rb$opts)
}

rb_log_step_end = function(rb, step) {
  repbox_log_step_end(rb$project_dir, step)
}

repbox_log_step_start = function(project_dir, step, opts) {
  step.info.dir = file.path(project_dir,"steps")
  if (!dir.exists(step.info.dir)) dir.create(step.info.dir, recursive = TRUE)
  file = paste0(step.info.dir, "/",step,".start.Rds")
  saveRDS(list(start_time=Sys.time(), opts=opts), file)
}

repbox_log_step_end = function(project_dir, step) {
  step.info.dir = file.path(project_dir,"steps")
  file = paste0(step.info.dir, "/",step,".end.Rds")
  saveRDS(list(end_time = Sys.time()), file)
}


example_update_step = function() {
  library(repboxRun)
  library(repboxEJD)

  project_dirs = list.dirs("~/repbox/projects_gha",recursive = FALSE, full.names = TRUE)

  which(endsWith(project_dirs,"aer_108_6_7"))
  project_dirs = project_dirs[-c(1:291)]
  project_dir = project_dirs[1]
  for (project_dir in project_dirs) {
    cat("\n", project_dir,"\n")
    steps = repbox_steps_from(map = TRUE,html=FALSE)
    opts = repbox_run_opts(stop.on.error = !TRUE,timeout = 5*60, art_opts = repbox_art_opts(overwrite=TRUE))

    cat("\nFind table refereences in code...")
    library(repboxCodeText)
    res = code_project_find_refs(project_dir = project_dir, parcels=NULL)

    repbox_run_project(project_dir,lang="stata", steps=steps, opts=opts)
  }
  rstudioapi::filesPaneNavigate(project_dir)
}
